/**
 * Static Accounts
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountRequest } from './accountRequest';


/**
 * Account Details object definition
 */
export interface AccountDetails extends AccountRequest {
    /**
     * Unique account Id of the account generated by the system
     */
    id?: string;
}
export namespace AccountDetails {
}
