/**
 * Static Accounts
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';


/**
 * Account request object definition
 */
export interface AccountRequest {
    /**
     * The unique name of the entity associated to the user. This can be null in case of a user not associated to an entity.
     * In case of a account being linked to all entities, the field should be sent as *
     */
    entityShortName?: string;
    /**
     * The account number of the account to be added
     */
    number: string;
    /**
     * The currency of the account
     */
    currency: string;
    /**
     * The description of the account
     */
    description?: string;
    /**
     * The type of the account
     */
    type: AccountRequest.TypeEnum;
    address?: Address;
}
export namespace AccountRequest {
    export type TypeEnum = 'BBAN' | 'IBAN' | 'UPIC' | 'OTHER';
    export const TypeEnum = {
        BBAN: 'BBAN' as TypeEnum,
        IBAN: 'IBAN' as TypeEnum,
        UPIC: 'UPIC' as TypeEnum,
        OTHER: 'OTHER' as TypeEnum
    };
}
