/**
 * Static Accounts
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountDetails } from './accountDetails';
import { Meta } from './meta';


/**
 * View List of accounts object definition
 */
export interface AccountDetailsList {
    /**
     * List of accounts
     */
    items?: Array<AccountDetails>;
    meta?: Meta;
}
