/**
 * Static Accounts
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Address definition
 */
export interface Address {
    /**
     * The address line 1 of the address of the corporate
     */
    line1?: string;
    /**
     * The address line 2 of the address of the corporate
     */
    line2?: string;
    /**
     * The address line 3 of the address of the corporate
     */
    line3?: string;
    /**
     * The address line 4 of the address of the corporate
     */
    line4?: string;
}
