/**
 * Tasks Management
 * Create a task for the corporate or bank user
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Bank definition
 */
export interface BankUserDetails {
    /**
     * The full name of the bank for whom the task is assigned
     */
    bankName?: string;
    /**
     * The abbreviated name of the bank for whom the task is assigned
     */
    bankShortName?: string;
    /**
     * Select whether to send notification on any event occuring on this item for the bank
     */
    emailNotificationRequired?: string;

    email?: string;
}
