/**
 * Beneficiary Maintenance
 * Finastra's Beneficiary Maintenance API creates a request to save a beneficiary for funds transfer. It also allows to make changes to the existing beneficiary or delete the beneficiary itself. 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Beneficiary Definition
 */
export interface FTBeneficiary { 
    /**
     * The unique name of the entity associated to the user. This can be null in case of a user not associated to an entity
     */
    entityShortName?: string;
    /**
     * Name of the beneficiary
     */
    name?: string;
    /**
     * Beneficiary account number
     */
    accountNumber?: string;
    /**
     * Beneficiary account currency
     */
    currency?: string;
    /**
     * The nickname of the beneficiary
     */
    nickname?: string;
    /**
     * Defines whether the beneficiary to be created as active or inactive. If the beneficiary is active, it means that the beneficiary can be used for initiating the payments. If marked as inactive, the beneficiary cannot be used to initiate the payment
     */
    active?: boolean;
    /**
     * The type of beneficiary, whether pre approved or not. If the value is true, then the beneficiary is marked as pre approved. This beneficiary can only received funds from pre approved debit accounts. If this value is false, then the beneficiary is marked as non pre approved. This beneficiary can receive funds from pre approved as well as non pre approved debit accounts
     */
    preApproved?: boolean;
    /**
     * The threshold transfer limit allowed for the beneficiary
     */
    limitAmount?: string;
    /**
     * The currency of the threshold transfer limit allowed for the beneficiary
     */
    limitCurrency?: string;
    /**
     * The SWIFT BIC Code of the intermediary bank
     */
    bicCode?: string;
    /**
     * Bank Name of the beneficiary
     */
    bankName?: string;
    /**
     * Address of the intermediary bank
     */
    bankAddress?: string;
    /**
     * ISO Country code of the intermediary bank
     */
    country?: string;
    /**
     * Clearing code of the intermediary bank
     */
    clearingCode?: string;
    /**
     * Address of the beneficiary
     */
    beneficiaryAddress?: string;
    /**
     * The address of the branch of the bank
     */
    branchAddress?: string;
    /**
     * The Sub Product Code for each fund transfer type
     */
    subProductCode?: string;
    /**
     * Unique account Id of the beneficiary generated by the system
     */
    accountId?: string;
    /**
     * The SWIFT BIC Code of the intermediary bank
     */
    intermediaryBankBicCode?: string;
    /**
     * Name of the intermediary bank of the beneficiary
     */
    intermediaryBankName?: string;
    /**
     * Address of the intermediary bank
     */
    intermediaryBankAddress?: string;
    /**
     * ISO Country code of the intermediary bank
     */
    intermediaryBankCountry?: string;
    /**
     * Clearing code of the intermediary bank
     */
    intermediaryBankClearingCode?: string;
}
