/**
 * Counterparty Maintenance
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Contact Information definition
 */
export interface ContactInformation {
    /**
     * The name of the contact person of the counterparty
     */
    name?: string;
    /**
     * The contact number of the contact person of the counterparty
     */
    phone?: string;
    /**
     * The fax number of the contact person of the counterparty
     */
    fax?: string;
    /**
     * The telex number of the contact person of the counterparty
     */
    telex?: string;
    /**
     * The business entity identifier (BEI) code of the counterparty
     */
    bei?: string;
    /**
     * The address line 3 of the postal address of the counterparty
     */
    email: string;
    /**
     * The website of the counterparty
     */
    website?: string;
}
