/**
 * Counterparty Maintenance
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CounterpartyRequest } from './counterpartyRequest';


/**
 * Counterparty Details object definition
 */
export interface CounterpartyDetails extends CounterpartyRequest {
    /**
     * Unique counterparty Id of the counterparty generated by the system
     */
    id?: string;
}
