/**
 * Counterparty Maintenance
 * marketing material to be updated
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContactInformation } from './contactInformation';
import { PostalAddress } from './postalAddress';
import { SwiftAddress } from './swiftAddress';


/**
 * Counterparty request object definition
 */
export interface CounterpartyRequest {
    /**
     * The unique name of the entity associated to the user. This can be null in case of a user not associated to an entity.
     * In case of a counterparty being linked to all entities, the field should be sent as *
     */
    entityShortName?: string;
    /**
     * The name of the counterparty to be added
     */
    name: string;
    /**
     * The unique name of the counterparty
     */
    shortName: string;
    postalAddress?: PostalAddress;
    swiftAddress: SwiftAddress;
    /**
     * Identifier of the country. Adheres to ISO 3166 alpha 2
     */
    country?: string;
    contactInformation?: ContactInformation;
}
