/**
 * Corporate User Profile
 * The Corporate User Profile API provides the information on the corporate banking customers user's:
 * bank, corporate details, corporate entity, user details and the access level privileges.
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Entity } from './entity';
import { Meta } from './meta';


/**
 * List of the entities mapped to the corporate user
 */
export interface Entities {
    /**
     * List of entities
     */
    items?: Array<Entity>;
    meta?: Meta;
}
