/**
 * Tasks Management
 * Create a task for the corporate or bank user
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Issuer definition
 */
export interface IssuerDetails {
    /**
     * The user id of the authenticated user who is creating a task
     */
    userId?: string;
    /**
     * The company abbreviated name of the authenticated users company who is creating a task
     */
    issueCompanyShortName?: string;
    /**
     * Select whether to receive notification on any event occuring on this item for the authenticated user
     */
    emailNotificationRequired?: string;
    /**
     * The email id of the issuer user to whom the notification is to be sent
     */
    email?: string;
}
