/**
 * Several Transaction approvals
 * API allows a corporate user to approve or reject multiple transactions pending for approval.
 *
 * OpenAPI spec version: TBD
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SubmissionResponseItems {
// tnx id
  eventId?: string;
// ref id
  id?: string;
  /**
   * localization key of the message
   */
  messageId?: string;
  /**
   * message
   */
  message?: string;
}
