/**
 * Several Transaction approvals
 * API allows a corporate user to approve or reject multiple transactions pending for approval.
 *
 * OpenAPI spec version: TBD
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubmissionResponseItems } from './submissionResponseItems';

/**
 * bulk transaction approval response
 */
export interface SubmissionResponse {
  /**
   * list of transactions and their submission status
   */
  items?: SubmissionResponseItems[];
}
