/**
 * Tasks Management
 * Create a task for the corporate or bank user
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Tasks information
 */
export interface TaskDetails {
    name?: string;
    /**
     * The type of the task whether public or private. If private,
     * it will be assigned to a single user. If public it will be visible to all the users
     */
    type?: string;
    /**
     * Specifies the assignee of the task.
     */
    assignee?: string;
    /**
     * Specifies the description provided during task creation
     */
    description?: string;
    id?: string;
    eventId?: string;
    /**
     * Date on which the task was created by the user, in ISO 8601 format YYYY-MM-DD
     */
    issueDate?: string;
    /**
     * System generated to do list id.
     * This is the parent id when the task is created for the first time.
     *  All the tasks created for a particular transaction are given the same toDoListId.
     * This should be left blank when a task is created for the first time for a transaction.
     *  For the subsequent tasks creation for the same transaction, this field should be sent
     */
    toDoListId?: string;
    /**
     * Date and time on which the task was created by the user, in ISO 8601 format YYYY-MM-DDThh:mm:ss.sssZ
     */
    inputDateAndTime?: Date;
}
// export namespace TaskDetails {
//     export type TypeEnum = 'PUBLIC' | 'PRIVATE';
//     export const TypeEnum = {
//         PUBLIC: 'PUBLIC' as TypeEnum,
//         PRIVATE: 'PRIVATE' as TypeEnum
//     };
//     export type AssigneeEnum = 'OTHER-USER' | 'BANK-USER' | 'COUNTERPARTY-USER';
//     export const AssigneeEnum = {
//         OTHERUSER: 'OTHER-USER' as AssigneeEnum,
//         BANKUSER: 'BANK-USER' as AssigneeEnum,
//         COUNTERPARTYUSER: 'COUNTERPARTY-USER' as AssigneeEnum
//     };
// }
