-- Insert Bank Data

insert into GTP_BANK_DATA (ID, TYPE, NAME, BANK_NAME, STATUS, PARENTID, ADDRESS, POSTCODE, CITY, COUNTRY, BANK_CODE, BRANCH, INST_ID_NAME, INST_ID_VALUE, BIC, SWIFTCATEGORY, INTERNAL, BRANCH_INDICATOR) 
values ('1000001', '01', 'INTESA SANPAOLO SPA (FORMERLY BANCA INTESA SPA)', 'DEMOBANK', null, null, 'VIALE DELL OCEANO PACIFICO, 251', '144 ROMA', 'ROMA', 'US', null, null, 'INTESA SANPAOLO SPA', null , 'BCITIT32745', null, null, null);
