/*jsl:ignoreall*/
({
	// global localization strings
	"g_strGlobalDateFormat" : "yyyy/MM/dd",
	"g_blnSWIFTChecking" : "真",
	"g_delExtraLinesTextarea" : "错误",

	// in function of the data model, numbers before and after the comma, used for control in rate.xsl
	"g_numbersBeforeComma" : "6",
	"g_numbersAfterComma" : "8",
	"view_label" : "查看",
	"delete_label" : "删除",

	//Default number of renewals
	"default_rewnewalNumber" : "1",
	// Change in Status Dynamically
	"Approved" : "已授权",
	"Not_Processed" : "未处理",
	"Cancelled" : "取消",
	"mandatoryconfirmingBank" : "* 保兑行",
	"resendTransactionsConfirmation" : "您要重新发送${0} 交易. <br> 您确认么?",

	// Error messages
	"recipientMandatory" : "您必须选择收件人",
	"offsetMandatory" : "您必须选择抵消",
	"invalidCurrencyError" : "币种 ${0} 为无效币种",
	"invalidDayInMonthError" : "没有 '${0}' 在 ${1} ${2}",
	"invalidMonthError" : "${0} 为无效月份",
	"invalidYearError" : "${0} 为无效年份",
	"invalidDateError" : "${0} 为无效日期 (${1})",
	"invalidNumber" : "此字段必须包含一个有效数字",
	"invalidPayeeName" : "收款人名称不能超过35个字符",
	"invalidAction" : "此操作无效",
	"messageTypeELMessage" : "消息类型",
	"missingLogo" : "缺少标识",
	"settlementFreeFormatMessage" : "请在这里输入其他指令(如有)。例如：文档的处理指令",
	"acceptanceFreeFormatMessage" : "请在这里输入其他指令(如有)。",
	"correspondenceFreeFormatMessage" : "请在这里输入其他指令(如有)。",
	"transferExpiryDateLessThanIssueDateError" : "转账到期日 (${0}) 必须晚于 <br> 发行日期 (${1})",
	"transferExpiryDateGreaterThanExpiryDateError" : "转账到期日 (${0}) 必须早于 <br> 此到期日 (${1})",
	"transferLastShipmentDateLessThanTransferExpiryDateError" : "转账最迟装运日期 (${0}) 必须早于 <br> 转账到期日 (${1}).",
	"validFromDateGreaterThanValidToDateError" : "有效日期从 (${0}) 必须早于或者等于 <br>有效日期到 (${1}).",
	"invalidTransferNumbers" : "此字段必须包含0到999之间的有效数字",
	"invalidBlankEndorsedPercentage" : "此字段必须包含110到999之间的有效数字",
	"issueDateLessThanAppDateError" : "开立日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"paymentDueDateDateLessThanAppDateError" : "付款到期日(${0}) 必须晚于或者等于 <br>申请日期 (${1}).",
	"issueDateMoreThanAppDateError" : "发票签发日期 (${0}) 必须早于或者等于 <br>申请日期 (${1}).",
	"maturityDateLessThanAppDateError" : "到期日 (${0}) 必须晚于或等于申请日期 <br> (${1})。",
	"IssueDateGreaterThanMaturityDateError" : "签发日期 (${0}) 必须早于或者等于 <br>到期日 (${1}).",
	"invoiceDateGreaterThanDueDateError" : "发票日期 (${0}) 必须早于或等于 <br> 截止日期 (${1})",
	"dueDateLessThanAppDateError" : "截止日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"dueDateLessThanInvoiceDateError" : "截止日期 (${0}) 必须晚于或等于 <br> 发票日期 (${1})",
	"awbIssueDateLessThanAppDateError" : "AWB 开立日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"lastAnwerDateLessThanIssDateError" : "最迟答复日期 (${0}) 必须晚于或等于 <br> 开立日期 (${1})",
	"issueDateGreaterThanExpiryDateError" : "开立日期 (${0}) 必须早于 <br> 到期日 (${1})",
	"expiryDateLessThanIssueDateError" : "到期日 (${0}) 必须晚于或等于 <br> 开立日期 (${1}).",
	"maturityDateLessThanIssueDateError" : "到期日 (${0})必须晚于等于  <br>签发日期 (${1}).",
	"lastAnswerDateGreaterThanExpDateError" : "最迟答复日期 (${0}) 必须早于 <br> 到期日 (${1})",
	"issueDateGreaterThanMaturityError" : "开立日期 (${0}) 必须早于或等于 <br> 到期日 (${1}).",
	"lastShipmentDateLessThanAppDateError" : "最迟装运日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"lastShipmentDateGreaterThanIssDateError" : "最迟装运日期 (${0}) 必须早于开立日期 (${1})",
	"requestDateLessThanProcessingDateError" : "请求日期 (${0}) 必须晚于或等于 <br> 处理日期 (${1})",
	"requestDateLessThanAppDateError" : "请求日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"processingDateLessThanAppDateError" : "处理日期 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"expiryDateLessThanAppDateError" : "到期日 (${0}) 必须晚于或等于 <br> 申请日期 (${1})",
	"lastShipDateGreaterThanAmdDateError" : "最后装船日期 (${0}) 必须晚于或者等于 <br>修改日期 (${1}).",
	"expiryDateLessThanLastShipmentError" : "到期日 (${0}) 必须晚于或等于最后发货日期 <br> (${1})。",
	"originalexpiryDateLessThanLastShipmentError" : "原始到期日(${0}) 必须晚于或者等于<br>t最晚装船日期 (${1}).",
	"newexpiryDateLessThanOldShipmentError" : "新的到期日期 (${1}) 必须晚于或者等于 <br>之前的装船日期 (${0}).",
	"dueDateLessThanLastShipmentError" : "到期日 (${0}) 必须晚于或者等于 <br>最后装船日期 (${1}).",
	"amendDateLessThanIssueDateError" : "修改日期 (${0}) 必须晚于或等于开证日期 <br> (${1})。",
	"amendDateGreaterThanExpiryDateError" : "修改日期 (${0}) 必须早于或等于新的到期日期 <br> (${1})。",
	"orgExpDateGreaterThanExpiryDateError" : "新的到期日 (${0})必须晚于或者等于 <br>原始到期日期 (${1}).",
	"executionDateLessThanAppDateError" : "执行日期 (${0}) 必须晚于或等于申请日期 <br> (${1})。",
	"lastMatchDateGreaterThanIssDateError" : "最后匹配日期 (${0}) 必须早于开证日期 (${1})。",
	"lastMatchDateGreaterThanAppDateError" : "最后匹配日期 (${0}) 必须早于申请日期 (${1})。",
	"toleranceExclusivityError" : "正负增减量与最大 <br> 信用证金额中只能选一个。",
	"mandatoryFieldsError" : "必须填充所有必填字段。",
	"passwordSameAsLoginIdError" : "密码不能和用户登录名相同.",
	"mandatoryFieldsInTabError" : "此选项卡包含仍未填充的必填字段 <br>。",
	"mandatoryFieldsToSubmitError" : "所有字段都必须处于有效状态以提交交易。",
	"custAbbvNameEmptyError" : "请输入简称在 <br>保存客户档案之前.",
	"externalAccount_noEmptyError" : "请输入账户号码在 <br> 保存外部账户之前.",
	"userLoginIdEmptyError" : "请在<br>保存用户档案之前输入登陆ID.",
	"detailsUncompletedError" : "需要验证 <br> 一些信息以提交交易。",
	"textareaLinesError" : "字段中的行数超过了其最大值 (${0} 行)。",
	"textareaLinesCharsError" : "字段的大小超过其最大值 (${0} 行 x ${1} 个字符)。",
	"irrevocableStandByError" : "备用信用证必须是不可撤销的方可转让。",
	"amendAmountLessThanOriginalError" : "减少的金额不能大于当前金额。",
	"noAmendmentError" : "为使交易有效，必须至少对 <br> 一个输入字段加以修改。",
	"browserNotSupportedError" : "很抱歉，您的浏览器不支持此功能。 <br> 您可参考推荐浏览器清单以解决此问题。",
	"mandatoryTemplateFieldError" : "如果您要将 <br> 您的交易信息保存为模板，模板 ID 是必需字段。",
	"maximumValueError" : "新金额超过授权的最大值。",
	"illegalSWIFTCharError" : "基于所选SWIFT发送模式，您的交易中发现非法字符 '${0}' <br> 。请更正相关的字段 <br> ，允许的字符集包括以下字符： <br>......zA...Z0...9 /-?:().,'+",
	"illegalCharErrorContact" : "对于此域来说此数值不是一个有效的数值. 只有数字以及特殊字符 '-' 和 '+' 才可以被允许使用.",
	"illegalCharErrorContactForFax" : "这不是有效的传真号码。此字段仅允许使用数字和特殊字符'-'，'+'和'（）'",
	"illegalCharError" : "此字段不允许字符 '${0}' 。",
	"illegalSwiftCharError" : "无效Swift 字符.",
	"illegalPasswordError" : "此字段不允许字符 '${0}' 。",
	"mandatoryNarrativeError" : "增加或减少交易金额时，<br>必须在备注字段中说明修改原因。",
	"duplicateItemError" : "您的列表中已存在此项目。请重命名。",
	"duplicateEmail" : "邮件 1 和 邮件 2 不能相同.",
	"invalidPasswordCharError" : "The password is invalid. (The password length should be between ${0} and ${1} characters )",
	"invalidPasswordLengthError" : "密码无效。(密码长度应在 {0} 和 ${1} 个字符之间)",
	"passwordMandatory" : "密码不能为空。",
	"invalidPasswordError" : "密码无效 (密码必须最少 ${0} 个字符，<br>，和至少包括一个数字和一个字母)。",
	"changepasswordMandatory" : "请选择更改密码以继续。",
	"missingExchangeRateError" : "计算等值金额之前，您必须定义汇率。",
	"missingDocumentFormatError" : "您还没有选择所有提交的文件的格式。",
	"tooManyNewsLinksError" : "您必须选择此消息的一个且仅一个链接。",
	"tooManyEntriesError" : "很抱歉，最多允许${0} 条目。",
	"duplicateParameterError" : "在不同类型的列的标准中，已经使用此参数。<br> 请选择另一个参数。",
	"illegalTELEXCharError" : "基于所选的电传发送模式，非法字符 '${0}' <br> 存在于您的交易中。请更正相关的字段 <br> 。允许的字符集包括以下字符： <br> A.。Z0...9'()+,-./:=?",
	"columnWidthError" : "您已选择要使用相对列宽度。 <br> 因此各列的宽度的总和必须等于 100%，且所有列宽度必须都有一个值。",
	"shipmentPeriodOrDateMissingError" : "您必须至少选择 <br> 最迟装运日期或装运期限。",
	"mandatoryApplicantDetailsError" : "您必须填充申请人的信息。",
	"transferAmtGreaterThanLCAmtError" : "转账金额不能大于信用证金额。",
	"tooManyReportLinesError" : "报表执行时最大行数显示 <br> 必须介于 1 和 100 之间。",
	"tooManyReportProductsError" : "该报表不支持多产品。您不能添加另一种产品。",
	"mandatoryFrequenceError" : "您必须选择一个频率",
	"mandatoryDayOfWeekError" : "您必须选择该周的一天",
	"mandatoryDayOfMonthError" : "您必须填写该月的一天。",
	"invalidFieldSizeError" : "字段的大小超过其最大值 <br> (${0} 行 x ${1} 个字符)。",
	"invalidCountryCodeError" : "国家代码 (${0}) 无效",
	"mandatoryBeneficiaryError" : "您必须选择至少一个受益人。",
	"mandatoryPaymentTypeError" : "您必须选择至少一个付款类型和填充相关信息。",
	"mandatoryAmtOrRateError" : "您必须选择金额与率和百分比。",
	"mandatoryFreightChargeError" : "您必须首先选择货运收费类型。",
	"mandatoryPaymentTermError" : "您必须定义至少一个付款期限。",
	"tnxAmtGreaterThanInvAmtError" : "交易金额必须小于或者等于发票金额.",
	"mandatoryLineItemError" : "您必须定义至少一个行项目。",
	"invalidPhoneNoError" : "无效的电话或传真号码 (${0}) <br> (+ XXX YYYYYYYY)。",
	"invalidIBANAccNoError" : "无效的 IBAN 账号 (${0}) <br> (2 字母字符 + 2 号 + 无任何分隔符的 1 到 30 个字母数字字符)。",
	"invalidDebitChargeAccount" : "无效的收费账户(${0}) <br> 账户的货币应该是本地或汇款货币。",
	"invalidBBANAccNoError" : "无效的 BBAN 账号 (${0}) <br> (从 1 到 30 个字母数字字符，无任何分隔符)。",
	"invalidUPICAccNoError" : "无效 UPIC 账号 (${0}) <br> (从 8 到 17 数字，无任何分隔符)。",
	"mandatoryAirportError" : "您必须在每种运输方式中为每组空运确定至少一个目的地机场 <br>。 <br> 检查运载的货物的信息。",
	"mandatoryDischargePortError" : "您必须在每种运输方式中为每组海运确定至少一个卸货港 <br>。 <br> 检查运载的货物的信息。",
	"mandatoryRoadReceiptPlaceError" : "您必须在每种运输方式中为每组公路运输确定至少一个收货地 <br>。 <br> 检查运载的货物的信息。",
	"mandatoryRailReceiptPlaceError" : "您必须在每种运输方式中为每组铁路运输确定至少一个收货地 <br>。 <br> 检查运载的货物的信息。",
	"invalidBEIError" : "无效的BEI (${0})。 <br> BEI必须具有以下格式： 6 个字符 + 1 个除 0 和 1外的字母数字字符 <br> + 1 个从 A 到 N  、P 到 Z或 0 到 9的字母数字字符 <br> + 0 或 3 个字母和数字字符。",
	"invalidBICError" : "无效的BIC (${0})。 <br> BIC必须具有以下格式： 6 个字符 + 1 个除 0 和 1外的字母数字字符 <br> + 1 个从 A 到 N  、P 到 Z或 0 到 9的字母数字字符 <br> + 0 或 3 个字母和数字字符。",
	"invalidMeasureUniteError" : "该测量结合${0} 和 ${1} 不是同一类型。",
	"mandatoryDirectionError" : "您必须首先选择一个方向。",
	"tooManyGoodTypesError" : "每个行项目仅可选择一次货物类型。",
	"tooManyLastShipmentDatesError" : "最后“发货日期” 可能存在于采购订单部分或者行项目信息中，但不同时存在。 <br> 注： 不需要显示元素。",
	"tooManyRoutingSummariesError" : "路线概况可能存在于采购订单部分或者行项目信息中，但不同时存在。 <br> 注： 不需要显示详细信息。",
	"tooManyIncoTermsError" : "国际贸易术语解释通则可能存在于采购订单部分或者存在于行项目信息中，但不会同时存在。 <br> 注： 不需要显示国际贸易术语解释通则。",
	"invalidAirportCodeOrNameError" : "您必须选择机场代码或城市/机场名。",
	"mandatoryCurrencyCodeError" : "在输入交易信息之前，您必须选择币种代码。",
	"mandatoryIndividualTransportModeError" : "个别运输模式下，必须存在这种运输模式的至少一个元素。",
	"mandatoryMultimodalTransportModeError" : "多式联运运输模式下，必须存在这种运输模式的至少两个元素。",
	"invalidPaymentTermPercentageError" : "如果付款条件使用百分比，所有百分比的总和必须等于 100%。目前，这个总数是 ${0} %。",
	"mandatoryPaymentTermsError" : "您必须首先选择付款方式类型。",
	"tooManyPODetailsError" : "Inco Terms、 调整、 税款和运费可能存在于采购订单部分或行项目信息中，但不同时存在。 <br> 注： Inco Terms、 调整、 税款和运费可能并不存在。",
	"readonlyBICCodeError" : "您不能修改 BIC 代码。",
	"nonUniqueReferenceError" : "参考号必须是唯一的。值 (${0}) 已定义。",
	"secondLessThanFirstError" : "第二个值必须大于第一个值。",
	"shipmentDateOrPeriodExclusivityError" : "最迟装运日期和装运期 <br> 中只能选一个。",
	"invalidSWIFTFieldError" : "根据所选的SWIFT发送模式，在此字段中发现非法字符 <br>。",
	"toDateGreaterThanFromDateError" : "“到”日期 (${0}) 应早于或等于“从”日期 (${1})。",
	"toDateLessThanTodaysDateError" : "“到”日期 (${0}) 应早于今天的日期 (${1})。",
	"toDateLessThanOrEqualToTodaysDateError" : "选择的'到日期'(${0}) 必须早于或者等于当天日期 (${1}).",
	"actualRangeGreaterThanLimitRangeError" : "日期范围不能大于 (${0}) 天.",
	"fromDateLessThanTodaysDateError" : "“从”日期 (${0}) 应早于今天的日期 (${1})。",
	"fromDateLessThanOrEqualToTodaysDateError" : "日期从 (${0}) 必须早于或者等于今天日期 (${1}).",
	"dateRangeLimitError" : "指定的日期范围 (${0}) 不应超过前一天起 ${1} 天。",
	"entityInputError" : "因为只有一个公司 代码 可以输入或选择，不允许此输入。",
	"mandatoryBankError" : "您必须首先选择一家银行。",
	"generalCollaborationError" : "系统无法处理您的请求。缺少 HTML 元素",
	"generalTSUConsoleError" : "无效的值。",
	"generalLoginScreenError" : "您必须输入 ${0}。",
	"mandatoryPathToFileError" : "您必须输入文件的路径。",
	"mandatoryUploadFileNameError" : "您必须为此文件起名.",
	"invalidSWIFTFieldSizeError" : "此字段超过SWIFT信息中允许的最大大小 (100 行) 。 <br> 请切换到其他发送模式。",
	"confirmationInstructionsError" : "确定指令必须设置为确定或 <br> 可添加以激活此字段",
	"multipleChoiceError" : "您必须选择一个选项",
	"invalidSWIFTTransactionError" : "根据所选的SWIFT发送模式，在您的交易记录中找到非法字符<br>。请更正突出显示的字段， <br>允许的字符集包括以下字符： <br><b><br>a-z A-Z 0-9 \\/-?:().,'+</b>",
	"emptyMandatoryFieldsError" : "在此交易 <br> 中的一个或多个字段不正确!",
	"nonUniqueTemplateIDError" : "已存在具有相同 ID 的模板。是否要覆盖？",
	"emptyTemplateIDError" : "您不能用空 ID 保存模板",
	"invalidEmailAddressError" : "这不是一个有效的电子邮件地址。",
	"checkEmailId" : "给出的电子邮件ID数量超过10个",
	"invalidWebAddressError" : "这不是一个有效的网址。",
	"nonMatchingPasswordError" : "密码和确定密码的值必须相同。",
	"newPasswordSameAsOldPasswordError" : "新密码不能与旧密码相同",
	"generalServerError" : "在服务器上，出现了一个错误。请重试。",
	"rateMessageNumbersBeforeAndAfterComma" : "费率必须包含逗号前最多${0} 数字和逗号后最多 ${1} 数字。",
	"parityError" : "平价不能为 '0' (零) or 更少",
	"rateMessageDelimiter" : "率必须包含分隔符 '${0}'",
	"attachmentsMissingError" : "您必须附加文件 ('${0}')",
	"technicalError" : "出现技术错误，请再试一次",
	"technicalException" : "出现技术错误，请再试一次",
	"imageFormatNotSupported" : "图像格式不支持",
	"imageSizeInappropriate" : "图像大小不合适",
	"noMT700Uploaded" : "MT700 文件未上传 ！",
	"mandatoryData" : "至少需要输入一个数据。",
	"invoiceFileRequired" : "提交之前,需要提交发票文件.",
	"highlightedFieldsRequired" : "请在标注的域内填入内容.",
	"entityNotSelectedError" : "请先选择一个机构.",
	"beneficiaryCustomIDNotUnique" : "不能保存这个收款人.\n此收款ID已经存在 ${0}",
	"fetchingExchangeRates" : "正在获取汇率",
	"fxIncorrectAmount" : "请输入有效的金额 ！",
	"fxInBetweenContractError" : "合同字段间不能为空。请按顺序输入。",
	"FXContractNumber" : "合同编号：",
	"FXAmountToUtilise" : "要利用的金额：",
	"FXContractSequenceNote" : "外汇合同的使用将按上文所述顺序。",
	"FXTotalAmountToUtilise" : "要利用的总金额：",
	"sameBeneficiaryApplicantError" : "受益人账号不能与申请人账号相同 ！",
	"releaseAmtGreaterThanOrgLiabAmtError" : "释放金额不能大于未清偿金额. 金额同样不能等于零.",
	"canNotReleaseTheTransaction" : "释放金额不能大于未偿还金额,请检查剩余未偿还金额.",
	"canNotProceedTheTransaction" : "动作不能被执行因为交易已经在取消的状态.",
	"settlementAmtGreaterThanOrigTnxAmtError" : "清算金额 (${0})不能大于原始交易金额 (${1}). 同样金额不能为零.",
	"expiryDateSmallerThanOrgExpiryDate" : "新的有效日期 (${0})应当晚于原始有效日期 (${1}).",
	"expiryDateBiggerThanOrgExpiryDate" : "新的到期日期 (${0})必须早于原先的到期日期 (${1}).",
	"expiryDateSmallerThanIssueDate" : "新的有效日期 (${0}) 应当晚于签发日期 (${1}).",
	"expiryDateSmallerThanSystemDate" : "下一个到期日 (${0}) 必须晚于系统日期.",
	"endDateSmallerThanCurrentDate" : "最终日期 (${0}) 不能早于现有日期.",
	"reviewDateSmallerThanCurrentDate" : "复核日期不能早于当前日期.",
	"newExpDateSmallerThanCurrentDate" : "10",
	"lastShipDateBiggerThanOrgLastShipDate" : "新的最晚装船日期(${0}) 必须不能超过原始的最晚装船日期 (${1}).",
	"remittanceDateGreaterThanSystemDateError" : "付款日期 (${0})不能晚于系统日期.",
	"sgAmtGreaterThanLcLiabAmtError" : "提货担保金额必须大于或者LC 未清偿金额.",
	"amdDateSmallerThanCurrentDate" : "修改日期(${0}) 应当晚于当前日期.",
	"amdDateGreaterThanOldExpiryDate" : "修改日期(${0}) 应当早于之前的到期日 (${1}), 请提供新的到期日.",
	"amendDateGreaterThanOldExpiryDate" : "修改日期 (${0}) 应该早于之前到期日 (${1}).",
	"amdDateGreaterThanOldShipmentDate" : "修改日期 (${0})必须早于之前的装船日期(${1}), 提供新的装船日期.",
	"OldShipmentDateGreaterThanexpDate" : "到期日 (${0}) 必须晚于之前的装船日期 (${1}), 提供新的装船日期.",
	"amdDateGreaterThanExpiryDate" : "修改日期(${0}) 必须早于到期日期 (${1}).",
	"ExpiryDateLessThanamendDate" : "到期日 (${0}) 必须晚于修改日期 (${1}).",
	"amdDateGreaterThanShipmentDate" : "修改日期应当早于最晚装船日期 (${0})  (${1}).",
	"expiryDateLessThanTransDocDateError" : "到期日 (${0}) 必须晚于或者等于 <br>运输单据日期 (${1}).",
	"TransDocDateGreaterThanApplDateError" : "运输单据上的日期 (${0}) 必须早于 <br> 申请日期 (${1}).",
	"TransDocDateLessThanExpDateError" : "运输单据日期 (${0}) 必须小于 <br> 到期日 (${1}).",
	"AmtGreaterThanOrgOutstandingAmtError" : "赔偿金额不应超过原有债务总额 (${0})",
	"futureDateSmallerThanAppDate" : "到期日 (${0}) 必须晚于 <br> 申请日期 (${1}).",
	"issDateSmallerThanFutureDate" : "到期日 (${0}) 必须大于 <br> 签发日期 (${1}).",
	"mandatoryPOReferenceError" : "发票参考号已经存在.",
	"mandatoryCNReferenceError" : "贷记通知参考已经存在.",

	//FILE UPLOAD MANDATES
	"mandatoryMinimumFileUploadTypeError" : "至少一个文件已上传。",
	"mandatoryMaximumFileUploadTypeError" : "只有一个文件可以上传。",

	// confirmation messages
	"saveTransactionConfirmation" : "您将要保存当前的 <br> 交易信息。是否确定？",
	"forwardTransactionConfirmation" : "您将要转发 <br> 当前交易信息。是否确定？",
	"forwardsTransactionConfirmation" : "您将要转发 <br> 当前交易信息。是否确定？",
	"rejectTransactionConfirmation" : "您将要拒绝 <br> 当前交易信息。是否确定？",
	"returnTransactionConfirmation" : "您准备退回此笔交易所有细节 <br>, 请确认是否继续?",
	"submitTransactionConfirmation" : "您正在试图提交此笔录入，请确认",
	"submitTransactionConfirmationWithWarning" : "您将试图提交一笔 <br>输入数据有以下提示:<br />${0}<br />需要继续么?",
	"submitTransactionConfirmationForMasterBeneficiary" : "您试图提交 <br>输入数据. 确认么?",
	"submitTransactionConfirmationForBeneficiaryFileUpload" : "您将要试图提交 <br>输入数据. 是否确定?",
	"saveTemplateConfirmation" : "您将要将 <br> 交易信息保存为模板。是否确定？",
	"cancelTransactionConfirmation" : "您将要离开当前页面。<br> 是否确定？",
	"editTransactionConfirmation" : "您将要提交允许您 <br> 更新的交易数据。您要继续吗？",
	"deleteTransactionsConfirmation" : "您将要删除 ${0} 交易记录。<br> 请确认",
	"cancelledTransactionsConfirmation" : "您准备取消${0}交易. <br>请确认?",
	"zipTransactionsConfirmation" : "您将要导出到压缩 ${0} 交易记录。<br> 是否确定？",
	"noTransactionsSelectedError" : "您必须选择一项交易。",
	"deleteTransactionConfirmation" : "你正在从系统删除名为'${0}'的记录，请确认",
	"deleteTransactionConfirmationforEmptyTitle" : "您准备删除记录 <br>从系统. 您确定?",
	"deleteRecordConfirmation" : "您将要删除此记录。<br> 是否确定？",
	"switchSendingModeForDescGoodsConfirmation" : "您的货物描述超过SWIFT信息 (100 行) 中允许的最大大小 <br>。您是否 <br> 切换到其他发送模式？",
	"switchSendingModeForDocsRequiredConfirmation" : "您的所需文件列表超过SWIFT信息 (100 行) 中允许的最大值 <br> 大小。您是否要 <br> 切换到其他发送模式？",
	"switchSendingModeForAdditionalInstructionsConfirmation" : "您的附加说明超过SWIFT信息 (100 行) 中允许的最大值 <br>。您是否要 <br> 切换到其他发送模式？",
	"removeItemConfirmation" : "您将要删除此项目。是否确定？",
	"downloadFileConfirmation" : "您将要下载 ${0}的文件。是否确定？",
	"versionDocumentConfirmation" : "您将要去版本所选的文档。<br> 要继续吗？",
	"addDocumentConfirmation" : "您将要添加文档。<br> 要继续吗？",
	"deleteDocumentConfirmation" : "您将要删除文档。<br> 要继续吗？",
	"editDocumentConfirmation" : "您将要提交允许您 <br> 更新文档数据的表格。您要继续吗？",
	"editTemplateConfirmation" : "您将要提交允许您 <br> 更新模板数据的表格。您要继续吗？",
	"closeTemplateConfirmation" : "您是否要关闭该模板数据表格？",
	"changeTotalCurrencyConfirmation" : "您将要改变总货币。 <br> 可能丢失您的产品和收费表中的一些数据.<br> 是否确定？",
	"submitEUCPTransactionConfirmation" : "您将要尝试提交 <br> 当前交易。是否确定？ <br> <br> 注： ${0} 适用eUCP，<br> 请确保您已正确指定 <br> 所需的电子格式。",
	"currencyLimit" : "您正在试图提交此笔录入，请确认 <br> <font color= 'red'> 大额交易提醒：贵帐户非柜面转帐单日累计金额已接近/超过人民币100万元。请确认本次付款。 </font>",
	"currencyLimitConfirmation" : "您将要提交 ${0} 交易。<br> 是否确定？ <br> <font color= 'red'> 大额交易提醒：贵帐户非柜面转帐单日累计金额已接近/超过人民币100万元。请确认本次付款。 </font>",
	"submitTransactionsConfirmation" : "您将要提交 ${0} 交易。<br> 是否确定？",
	"changeProductConfirmation" : "更改产品将删除您当前报告配置。 <br> 是否确定？",
	"removeParameterConfirmation" : "参数 ${0} 使用的一个或多个 标准。<br> 删除此项，将删除与此关联的 标准。<br> 要继续吗？",
	"loadRecordsConfirmation" : "您将要加载 ${0} 记录。<br> 是否确定？",
	"missingLoadingOrDestinationConfirmation" : "尚未输入装货地点或 <br> 货物的最终目的地。<br> 您确定要提交交易信息吗？",
	"sendByTELEXConfirmation" : "您将要发送通过电传交易。<br> 您确定要提交交易信息吗？",
	"renameParameterConfirmation" : "一个或多个标准使用此参数。<br> 重命名此参数将会删除关联的 标准。<br> 要继续吗？",
	"changeComputedFieldConfirmation" : "此计算的字段用于一个或多个集合。<br> 更改该标识符将删除关联的集合。<br> 要继续吗？",
	"saveDataConfirmation" : "您将要保存您的数据。<br> 是否确定？",
	"modifyFundTransferCurrencyConfirmation" : "您将要修改转账货币。 <br> 此更改将删除或修改填充的受益人。是否确定？",
	"parameterAlreadyUsedInCriterionConfirmation" : "参数 ${0} 用于一个或多个标准。<br> 删除此项，将删除关联的标准。<br> 要继续吗？",
	"cancelMCTransactionConfirmation" : "您将要从系统中取消该记录 '${0}' <br> 。是否确定？",
	"revertMCTransactionsConfirmation" : "您将要从系统中拒绝该记录。<br> 是否确定？",
	"returnMCTransactionsConfirmation" : "您将要将记录退回操作员。<br> 是否确定？",
	"deleteMCTransactionsConfirmation" : "您将要从系统中删除该记录。<br> 是否确定？",
	"closeCommentsMandatory" : "收盘评论需要.",

	//Authorisation
	"mandatoryMinimumAuthorisationLevelError" : "必须添加至少一个授权级别",

	// Purchase Order
	"deleteRoutingSummariesConfirmation" : "您将要删除填充的路径摘要。<br> 是否确定？",
	"processPopulatedRecordsConfirmation" : "您将要处理填充的记录。<br> 是否确定？",
	"initiateLetterOfCreditsConfirmation" : "您将要发起信用证。<br> 是否确定？",
	"savePopulatedRecordsConfirmation" : "您将要将填充的记录保存到开户文件夹。<br> 是否确定？",
	"submitPopulatedRecordsConfirmation" : "您将要将填充的记录提交到开户文件夹。<br> 是否确定？",
	"resetCurrencyConfirmation" : "如果重置货币而不定义新货币，调整、 税费、 运费和行项目将被删除。<br> 是否确定？",
	"changePaymentTermsConfirmation" : "如果您更改付款条款信息 (金额或百分比)，以前的所有元素将被丢弃。<br> 是否确定？",
	"changeFreightChargesTypeConfirmation" : "如果您更改运费收费类型，以前的所有元素将被丢弃。<br> 是否确定？",
	// Collaboration Suite
	"associateCounterpartyConfirmation" : "您将要将此对手方与现有客户相关联。<br> 是否确定？",
	"removeCounterpartyConfirmation" : "您将要删除这些对手方的关联客户。<br> 是否确定？",
	"associateCustomerConfirmation" : "您将要将此客户 <br> 关联到先前所选的对手方。<br> 是否确定？",
	"deleteAttachedFileConfirmation" : "您将要删除此附加文件。 <br> 是否确定？",
	"deleteBeneficiaryConfirmation" : "您将要删除一个受益人。<br> 要继续吗？",
	"deleteChargeConfirmation" : "您将要删除收费。<br> 要继续吗？",
	//
	// Information messages
	//
	"bankPreviousSubmissionMessage" : "上次提交后来自银行的信息： <br> <br> ${0}",
	"monthDayWarningMessage" : "提示： 29、 30、 31 日并非所有月份都可用。",
	"dateMonthWarningMessage" : "日期范围无效，是强制字段且限于 ${0} 天",
	"mandatoryCurrencyMessage" : "您必须定义币种",
	"dateDayRangeValidityMessage" : "日期范围无效，是强制字段且限于 ${0} 个月",
	"dateMonthRangeValidityMessage" : "日期范围无效，是强制字段且限于 ${0} 天到 ${1})天",
	"monthRangeValidityMessage" : "日期范围仅限于 ${0} 个月",
	"dateRangeValidityMessage" : "开始日期应早于结束日期。",
	"mandatoryAccountFormatMessage" : "您必须首先选择账户格式。",
	"mandatoryTransshipmentMessage" : "若需要运输数据集，必须存在转运字段。",
	"mandatoryTransshipmentErrorMessage" : "如果转运设置为需要, 转运日期必须为现在<br> 如果船运细节没有提供, 请联系您的管理员.",
	"timeRemainingMessage" : "剩余时间： ${0} 分钟 ${0} 秒",
	"sessionExpiredMessage" : "会话已过期 ！",
	"sessionExpirationTimeMessage" : "您的会话将在 ${0} 分钟后过期。 <br> 请立刻保存您的工作以避免被注销。",
	"fileUploadSuccessMessage" : "文件 <b> ${0} </b> 已成功上传 ！<br> 您还可以上传 <b> ${1} </b> 个文件。",
	"fileUploadSucessMaxReachedMessage" : "文件 <b> ${0} </b> 已成功上传 ！<br> 您已附加最大数量的文件。",
	"fileDeleteSuccessMessage" : "文件 <b> ${0} </b> 已从交易中删除！<br> 现在还可以上传 <b> ${1} </b> 个文件。",
	"validatingTransactionMessage" : "正在验证交易...",
	"savingTransactionMessage" : "正在保存交易...",
	"forwardingTransactionMessage" : "正在转发交易......",
	"rejectingTransactionMessage" : "正在拒绝交易......",
	"returningTransactionMessage" : "返回交易 ...",
	"validatingAndSubmittingMessage" : "正在验证和提交...",
	"savingTemplateMessage" : "正在保存该模板 <b> ${0} </b>......",
	"deleteMessage" : "单击此处以确定此删除操作",
	"cancelMessage" : "取消",
	"okMessage" : "确定",
	"returnMessage" : "退回", 
	"autoForwardMessage" : "自动展期",
	"alertMessage" : "提示",
	"sessionalertMessage" : "会话信息",
	"errorMessage" : "错误",
	"confirmationMessage" : "确认",
	"resubmitMessage" : "重新提交 ...",
	"progressMessage" : "处理",
	"showFormSummaryMessage" : "显示表格摘要",
	"hideFormSummaryMessage" : "隐藏表格摘要",
	"mustChooseGuarantee" : "您必须首先选择一个保证。",
	"mustChooseStandByIssued" : "您必须首先选择一个备用开立模版.",
	"tabErrorWarning" : "此选项卡包含错误字段",
	"loadingMessage" : "正在加载...",
	"valueShouldBeInteger" : "输入值无效请输入一个整数",
	// TSU Console
	"maxTSUElementsMessage" : "您已超出最大授权元素数。",
	// Collaboration Suite
	"mandatoryEntityMessage" : "您应首先选择公司代码。",
	"transactionPopupWindowTitle" : "交易弹出式菜单",
	"pdfSummaryWindowTitle" : "交易PDF摘要",
	"onlineHelpWindowTitle" : "交易PDF摘要",
	// Report Designer
	"computedLabel" : "计算",
	"parameterLabel" : "参数",
	"addCriterium" : "添加标准",
	"updateCriterium" : "更新标准",
	"days" : "天数",
	"reportExecutionDate" : "报告执行日期",
	"firstDayOfCurrentMonth" : "当前月的第一天",
	"lastDayOfCurrentMonth" : "当前月的最后一天",
	"today" : "今天",
	"tomorrow" : "明天",
	"yesterday" : "昨天",

	// Loan
	"loanEffDateGreaterThanFacEffDateError" : "有效日期 (${0}) 必须晚于或者等于额度生效日期 (${1}).",
	"loanEffDateLessThanFacExpDateError" : "有效日(${0}) 必须早于等于额度到期日 (${1}).",
	"loanAmendDateGreaterThanFacExpDateError" : "提升的有效日期(${0})必须早于或者等于额度到期日期 (${1}).",
	"loanEffDateLessThanFacMatDateError" : "有效日期 (${0}) 必须早于或者等于额度到期日期 (${1}).",
	"effectiveDateGreaterThanSystemDate" : "有效日期 (${0}) 应该晚于或者等于系统日期.",
	"loanEffDateLessThanLoanMatDateError" : "生效日 (${0})必须早于等于到期日(${1}).",
	"loanMatDateLessThanLoanEffDateError" : "到期日 (${0}) 必须晚于或等于贷款的生效日期 <br> (${1})。",
	"loanRepricingDateGreaterThanLoanEffDateError" : "价格调整日期 (${0}) 必须晚于等于贷款生效日期 (${1}).",
	"loanRepricingDateLessThanLoanMatDateError" : "价格调整日期 (${0}) 必须早于或者等于贷款到期日期 (${1}).",
	"loanRepricingDateLessThanFacMatDateError" : "重新定价日期(${0})必须早于或等于该额度的到期日(${1})",
	"loanMatDateGreaterThanFacMatDateError" : "到期日 (${0}) 必须小于或等于该授信的到期日 <br> (${1})。",
	"loanAmountTooBigError" : "贷款金额必须小于或等于 ${0} ${1}。",
	"loanIncreaseAmtTooBigThanBorrowerCcyLimitAmtError" : "贷款金额增加额必须小于或者等于 <br />借款人额度币种限额 (${0}) ${1}.",
	"loanIncreaseAmtTooBigThanBorrowerLevelLimitAmtError" : "贷款金额增加额必须小于或者等于 <br />借款人额度限额 (${0}) ${1}.",
	"loanAmountTooBigThanBorrowerCcyLimitAmtError" : "贷款金额必须小于或者等于 <br />借款人额度币种限额 (${0}) ${1}.",
	"loanAmountTooBigThanBorrowerRiskTypeLimitAmtError" : "贷款金额必须小于或者等于 <br />借款人额度风险类型限额 (${0}) ${1}.",
	"loanIncreaseAmountTooBigError" : "贷款增加金额必须小于等于 ${0} ${1}.",
	"loanRepricingAmountTooBigError" : "重新定价贷款金额必须小于或者等于 ${0} ${1}. <br />请尝试选择不同的额度.",
	"loanRepricingAmountTooBigForCurrencyError" : "重新定价的贷款金额必须小于或者等于币种限额 (${0}) ${1} 针对额度 '<b>${2}</b>'. <br />请尝试选择其他额度.",
	"loanRepricingAmountTooBigForBorrowerError" : "重定价金额必须小于或者等于借款人额度 (${0}) ${1}. <br />请尝试选择不同的额度.",
	"loanAmountZeroError" : "贷款金额必须大于 0",
	"loanAmendDateGreaterThanLoanMatDateError" : "修改日期 (${0}) 必须早于或等于的贷款到期日 <br> (${1})。",
	"loanAmendDateLessThanLoanEffDateError" : "修改日期 (${0}) 必须晚于或等于贷款的生效日期 <br> (${1})。",
	"loanPayDateGreaterThanLoanMatDateError" : "付款日期 (${0}) 必须早于或等于贷款到期日 <br> (${1})。",
	"loanPayDateLessThanLoanEffDateError" : "付款日期 (${0}) 必须晚于或等于贷款的生效日期 <br> (${1})。",
	"loanEffectiveIncreaseDateLessThanCurrentDate" : "提高的有效日期 (${0}) 不能早于系统当前日期.",
	"loanAmendDateLesserThanLoanEffectiveDateError" : "额度增加生效日期 (${0})必须晚于贷款有效日期 (${1}).",
	"effectiveIncreaseDateGreaterThanLoanEffDateError" : "增加有效日期 (${0}) 不能晚于或者等于 <br>贷款到期日期 (${1}).",
	"loanFacilityAmtExceeded" : "贷款金额超过全球可用额度限额.",
	"loanBorrowerCcyLimtAmtExceeded" : "贷款金额大于借款人额度货币限制额度.",
	"loanBorrowerRiskTypeLimtAmtExceeded" : "贷款金额大于借款人风险类型限制额度",
	"loanBorrowerLevelLimtAmtExceeded" : "贷款金额大于借款人额度限额.",
	"loanRepricingAmountBigThanBorrowerCcyLimitAmtError" : "重定价的贷款额度必须小于或者等于 <br />借款人风险类型额度 (${0}) ${1}. <br />请尝试选择另外的风险类型.",
	"loanFacilityBorrowerCcyLimitAmtExceeded" : "贷款金额大于借款人全球货币额度限制金额.",
	"loanAmountTooBigThanBorrowerLimitAmtError" : "贷款金额必须小于或者等于 <br />借款人限制额度 (${0}) ${1}.",


	// Summit
	"payCashflowPopupTitle" : "支付现金流",
	"receiveCashflowPopupTitle" : "收入现金流",
	"paySchedulePopupTitle" : "支付计划",
	"receiveSchedulePopupTitle" : "收入计划",
	"errorHasOccured" : "出现错误。",
	"effectiveDateMustBeGreater" : "生效日期 (${1}) 必须晚于 <br> 开始日期 (${0})。",
	"effectiveDateMustBeLower" : "生效日期 (${0}) 必须早于 <br>结束日期 (${1})。",
	"mandatoryTerminationDate" : "您必须定义一个终止日期。",
	"fullPartialTermination" : "部分/全部终止",
	"mandatoryExpiryDate" : "您必须定义一个到期日。",
	"cancelTrade" : "取消此交易",
	"expiryTrade" : "到期此交易",
	"exerciseTrade" : "执行此交易",
	"exerciseDate" : "行权日",
	"exerciseAmt" : "行权金额",
	"underlyingCustomer" : "基础客户 =",
	"underlyingPortfolio" : "基础投资组合=",
	"settlementDate" : "交割日=",
	"settlementAmt" : "交割金额=",
	"unwind" : "展开=",

	"term_effective_date" : "生效日",
	"term_pay_leg_new_not" : "金额",
	"term_pay_leg_intrst" : "利息",
	"term_pay_leg_fee_amt" : "收费",
	"term_counterparty" : "交易对手",
	"term_new_call" : "看涨=",
	"term_new_put" : "看跌=",
	"term_fee_date" : "收费日期=",
	"term_fee_amt" : "收费=",
	"term_full" : "足期",

	"TRSFixingDateAlreadyExists" : "已为选定的证券定义确定日期。",
	"TRSFixingDateResetPriceAlreadyExists" : "已为选定的证券定义确定日期和重置价格。",
	"TRSSecurityAlreadyExists" : "证券已在篮子中",
	"TRSSecurityQuantityAlreadyExists" : "证券和数量已在篮子中。",

	"ESStockAlreadyExists" : "股票已在篮子中。",
	"ESStockQuantityAlreadyExists" : "股票和数量已在篮子中。",
	"ESFixingDateAlreadyExists" : "已为所选的股票定义确定日期。",
	"ESFixingDateResetPriceResetFxAlreadyExists" : "已经为所选的股票定义确定日期、重置价格和重置外汇交易 。",


	// Cash
	"clearMessage" : "确定要清除所有字段吗？",
	"errorFXDateMissing" : "您必须定义一个日期。",
	"cancelRequest" : "您将要拒绝该请求。<br> 是否确定？",
	"errorFXEqualsCurrencies" : "货币与相对货币不能相同。",
	"TermCodeError" : "条款代码必须是个正整数.",
	"DateLessThanDateOfDayError" : "起息日 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"optionDateLessThanDateOfDay" : "期权日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"optionDateGreaterThanValueDate" : "期权日期 (${0}) 必须早于或等于起息日 <br> (${1})。",
	"valueDateSmallerThanOptionDate" : "起息日 (${0}) 必须晚于或等于期权日期 <br> (${1})。",
	"errorFXRateNoLongerValid" : "不能处理您的请求。 <br> 率 (${0}) 不再有效。",
	"errorFXRateRejected" : "不能处理您的请求。 <br> 您的请求已被拒绝。",
	"errorFXCurrencyNotAvailable" : "不能处理您的请求。 <br> 货币 (${0}) 不可用。",
	"errorFXFarDateGreaterNearDate" : "远端日期 (${0}) 必须晚于或等于近端日期的 <br> (${1})。",
	"errorFXNearDateGreaterFarDate" : "近端日期 (${0}) 必须早于或等于远端日期 <br> (${1})。",
	"errorFXNearDateGreaterDateOfDay" : "近端日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"errorFXFarDateGreaterDateOfDay" : "远端日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"errorFXUnknownCurrency" : "不能处理您的请求。 <br> 货币 (${0}) 不可用。",
	"errorFXUnknownCounterCurrency" : "不能处理您的请求。 <br> 货币 (${0}) 不可用。",
	"errorFXServiceClosed" : "不能处理您的请求。 <br> 服务已关闭。请稍后再试",
	"errorFXServiceNotAuthorized" : "不能处理您的请求。 <br> 您未被授权处理此操作",
	"errorFXDateNotValid" : "不能处理您的请求。 <br> 日期 (${0}) 无效",
	"errorFXCurrencyDateNotValid" : "不能处理您的请求。 <br> 日期 (${0}) 无效。",
	"errorFXCounterCurrencyDateNotValid" : "不能处理您的请求。 <br> 日期 (${0}) 无效。",
	"errorXOTriggersNotValid" : "至少填写一个触发字段。",
	"expirationDateLessThanValueDate" : "到期日 (${0}) 必须晚于或等于起息日 <br> (${1})。",
	"valueDateGreaterThanExpirationDate" : "起息日 (${0}) 必须早于或等于到期日期 <br> (${1})。",
	"lessthanCurrentDate" : "到期日必须晚于等于现有日期.",
	"documentAmtGreaterThanLCAmt" : "文件金额应当少于或者等于未清偿金额",
	"maturityDateLessThanValueDate" : "到期日 (${0}) 必须晚于或等于起息日<br> (${1})。",
	"maturityDateLessThanDateOfDate" : "到期日 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"valueDateGreaterThanMaturityDate" : "起息日 (${0}) 必须早于或等于到期日 <br> (${1})。",
	"valueDateSmallerThanOrgValueDate" : "起息日 (${0}) 必须晚于或等于原始起息日<br> (${1})。",
	"valueDateGreaterThanOrgValueDate" : "起息日 (${0}) 必须早于或等于原始起息日 <br> (${1})。",
	"executionDateLessThanDateofDay" : "执行日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"debitAcctEqualsToCreditAcct" : "借记账户 (${0}) 必须不同于贷记账户(${1})。",
	"creditAcctEqualsToDebitAcct" : "贷记账户 (${0}) 必须不同于借记账户 (${1})。",
	"confirmationRejectRequest" : "您的请求已被拒绝。",
	"confirmationRejectTitle" : "请求被拒绝",
	"confirmationCancelRequest" : "您的请求已被取消。",
	"confirmationCancelTitle" : "取消请求",
	"firstDateGreaterThanDateofDay" : "第一个日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"nextDateGreaterThanDateofDay" : "下一日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"nextDateGreaterThanFirstDate" : "下一日期 (${0}) 必须晚于或等于第一个日期 <br> (${1})。",
	"finalDateGreaterThanDateofDay" : "最后日期 (${0}) 必须晚于或等于天的日期 <br> (${1})。",
	"finalDateGreaterThanNexttDate" : "最后日期 (${0}) 必须晚于或等于下一日期 <br> (${1})。",
	"transferCurrencyDifferentThanAccountsCurrencies" : "转账货币 (${0}) 必须等于借记账户货币 <br> (${1}) 或贷记账户货币 (${2})",
	"errorSplitAmountGreaterThanOriginalAmount" : "拆分金额不能大于或等于原始金额。",
	"errorSameAccount" : "您不能两次选择相同的账户。",
	"errorTransactionInInvalideState" : "转存前必须授权DCommencement 方式",
	"errorUpdateTDMaturityGreaterStartDate" : "转存到期日 (${0}) 必须晚于或等于开始日期 <br> (${1})。",
	"customerError" : "不能识别客户或账户信息",
	"transferDateLessThanAppDateError" : "转账日期 (${0}) 不能早于 <br> 申请日期 (${1})。",
	"startDateLessThanAppDateError" : "开始日期 (${0}) 不能早于 <br> 申请日期 (${1})。",
	"startDateLessThanCurrentDateError" : "开始日期 (${0}) 不能早于 <br> 当前日期 (${1})。",
	"startDateGreaterThanEndDateError" : "开始日期 (${0}) 不能迟于 <br> 结束日期 (${1})。",
	"endDateLessThanStartDateError" : "开始日期 (${0})必须早于或等于 <br> 结束日期 (${1})",
	"transferDateGreaterThanRegisteredEndDateError" : "转让日期 (${0}) 不能迟于 <br> 注册结束日期 (${1})。",
	"startDateGreaterThanRegisteredEndDateError" : "开始日期 (${0}) 不能迟于 <br> 注册结束日期 (${1})。",
	"endDateGreaterThanRegisteredEndDateError" : "结束日期 (${0}) 不能迟于 <br> 注册结束日期 (${1})。",
	"mandatoryDateField" : "您必须选择一个日期。",
	"titleLength" : "后台参考应该包含 ${0} 字节.",
	"customerInputCenterLength" : "客户输入中心的长度至少两个字节，且为字母数字形式.",
	"FromTo" : "开始值 必须小于或者等于到达值 .",

	//TD account summary
	"generalDetailsHeader" : "一般的详细信息",
	"entityLabel" : "公司代码",
	"accountNumberLabel" : "账号：",
	"accountNameLabel" : "账户名称：",
	"branchNameLabel" : "分行名称：",
	"accountTypeLabel" : "账户类型：",
	"typeLabel" : "类型：",
	"tdFootNote" : "<b> 注： </b> <br/>-余额和细节是指示性的 <br/>-其他详细信息请参阅您的存款回执单。",
	"depositNumber" : "存款编号",
	"productType" : "产品类型",
	"currency" : "币种",
	"principalAmount" : "本金金额",
	"valueDate" : "记息日",
	"tenor" : "期限",
	"maturityDate" : "到期日",
	"interestRate" : "年化利率(%)",
	"interestAmount" : "合同利息",
	"remark" : "备注",
	"backToSummary" : "<U> 返回至账户摘要 </U>",
	"tdSummaryTitle" : "${0} 详情",
	"export" : "导出",

	// Transaction popup
	"TransactionLink" : "交易",
	"NoTransactionLink" : "交易记录",

	// Account popup
	"acct_no_header_label" : "账号",
	"description_header_label" : "描述",
	"bank_title_label" : "银行：",

	"currencyTableLabel" : "币种",
	"accountTableLabel" : "账户",
	"instructionIndicatorTableLabel" : "指令指示符",
	"beneficiaryInstitutionTableLabel" : "受益机构",
	"beneficiaryAccountTableLabel" : "受益人账户",
	"institutionAccountTableLabel" : "机构账户",

	// sweep
	"noSweepingMethodLabel" : "您必须选择一个归集方法！",
	"noSweepingMethodtTitle" : "无归集方法",
	"noSweepingFrequencyLabel" : "您必须选择一个频率！",
	"noSweepingFrequencyTitle" : "没有归集频率",
	"noAccountLabel" : "您必须添加一个帐户！",
	"noAccountTitle" : "无添加的帐户",
	"noConcentrationAccountLabel" : "您必须先选择一个集中账户",
	"noConcentrationAccountTitle" : "无集中帐户",
	"deleteAttachedAccountConfirmation" : "您将删除此附加的账户 <br> 您确定吗？",
	"deleteAccountConfirmation" : "您将删除此附加的帐户 '${0}'。<br>您要继续吗？",
	"deleteBillPayeeConfirmation" : "您将删除此附加条例的收款人 '${0}'。<br> 您要继续吗？",
	"accountAlreadySelectedLabel" : "该账户已被选中。您必须选择另一个。",
	"accountAlreadySelectedTitle" : "账户已选定",
	//Cashflows and schedule related strings
	"START_DATE" : "启动",
	"END_DATE" : "结束",
	"FLOW_DATE" : "流动日期",
	"DEFPROB" : "默认问题",
	"CUMULDEFPROB" : "累计的默认问题",
	"NPV" : "净现值",
	"RATE" : "利率",
	"DATE" : "日期",
	"PREMIUMFLOW" : "溢价流动",
	"PREMIUMDISCRATE" : "溢价折扣率",
	"ENTITYFUTFLOWS" : "机构未来资金流动",
	"ENTITYDISCRATE" : "机构折扣率",
	"RECRATE" : "启动率",
	"REFOBLIGFLOW" : "参考流入责任",
	"REFOBLIGDISCRATE" : "参考折扣率责任",
	"ENTITYPV" : "机构现值",
	"REFOBLIGPV" : "参考现值责任",
	"PREMIUMPV" : "溢价现值",
	"PRICE_FIX" : "价格固定",
	"CCY" : "币种",

	"PREMIUMDISCFACTOR" : "溢价折扣要素",
	"ENTITYDISCFACTOR" : "机构折扣要素",
	"EXPECTEDLOSS" : "预期损失",


	"PAY_DATE" : "支付日期",
	"FIX_DATE" : "确定日期",
	"AMOUNT" : "金额",
	"BASIS" : "基础",
	"TYPE" : "类型",
	"CUSTOM" : "自定义",
	"NOTICE" : "公告",
	"DELIVERY" : "交付",
	"OWNERSHIP" : "所有权",
	"EORA" : "EORA",
	"AMORT_S" : "AmortS",
	"AMORT_E" : "AmortE",

	"FIXNG" : "确定",
	"TRADE_DATE" : "贸易",
	"FORWARD" : "远期",
	"IDAYS" : "天数",
	"SPREAD" : "利差 (利润点)",
	"NOTIONAL" : "名义",
	"FLOWS" : "流动",
	"DAYS" : "天",
	"CURRENCY" : "币种",
	"FIXING" : "确定",
	"INTEREST" : "利息",
	"EV_TYPE" : "事件类型",
	"ZERO" : "零",
	"DISCOUNT" : "折扣",
	"PRESENT_VALUE" : "现值",
	"QUANTITY" : "数量",
	"INT_DAYS" : "利息天数",
	"FWD_RATE" : "远期汇率",
	"FX_RATE" : "外汇汇率",
	"STRIKE" : "执行汇率",
	"ALL_IN_RATE" : "总利率",
	"AUX_RATE" : "辅助利率",
	"EV_CCY" : "等值货币",
	"ZERO_RATE" : "零利率",
	"DISC_RATE" : "折扣率",
	"CCY_NPV" : "净现值币种",
	"FEE_NPV" : "净现值费用",
	"CCYDATALINK" : "币种数据链接",
	"INTERIM_INTEREST" : "临时的利息",
	"RETURN_START" : "回报开始日",
	"NOTIONAL_RATE" : "名义利率",

	"Cashflows" : "现金流详细信息",
	"Schedules" : "日程详细信息",
	"mandatoryReportProduct" : "一个产品组合报告必须至少基于一个产品",
	"mandatoryReportColumn" : "您必须至少选择一个报告列",
	"mandatoryReportCriteriumOperandType" : "您必须至少选择一个操作数标准类型 <br> (参数、 值或 预定义值)",
	"uploadingFile" : "正在上传文件…",
	"uploadingLogo" : "上传标志...",
	"authenticationError" : "您未通过身份认证或您将中断会话",
	"dateIsHoliday" : "日期 ${0} 是无效的，它不是一个交易日期",
	"repaymentPrincipalError" : "作为支付部分款项，还款金额应小于未偿还总额",
	"repaymentPrincipalInterestError" : "作为支付部分款项，还款金额应小于未偿还金额和利息总和",
	"mustChooseFinanceType" : "您必须首先选择一个融资类型",
	"auditDialogTitle" : "审核对话框",
	"businessCalendarTechnicalError" : "无法初始化日历，请再试一次",
	"holidayValidateError" : "您输入的日期 (${0}) 不能通过验证，请稍后再试",
	"focusOnErrorAlert" : "很抱歉，您必须更正您的输入以继续",
	"outstandingAmountShouldBeZero" : "清除事件处理之前，未偿还总额应为零。",
	"presentationAmountLessThanBaseAmount" : "提示金额 ${0} 必须小于基本金额 ${1}",
	"edit" : "编辑",
	"download" : "下载",
	"disclaimer" : "免责声明",
	"generalFromDateGreaterThanToDate" : "${0} 日期从'(${1}) 必须早于或者等于 <br>  '${0} 日期到'(${2})",
	"generalToDateGreaterThanFromDate" : "日期 '${0} 到'(${1}) 必须晚于或者等于 <br>  '${0} 日期从'(${2})",
	"thisDateGreaterThanCurrentDate" : "${0}日期 (${1})必须早于或者等于 <br> 当前日期",
	"upload" : "上传",
	"lastModified" : "最后修改",
	"ApplicationDate" : "Application",
	"TransferDate" : "Transfer Date",
	"maturityFromGreaterThanMaturityTo" : "从到期日必须早于或等于至到期日<br>",
	"maturityToLesserThanMaturityFrom" : "至到期日必须是晚于或等于 <br> 从到期日",
	"LastModifiedFromGreaterThanLastModifiedTo" : "最后修改日期from 必须早于等于 <br> 最后修改日期 To",
	"LastModifiedToLesserThanLastModifiedFrom" : "最后修改日期 to 必须晚于等于 <br> 最后修改日期 From",
	"BeneficiaryNameExists" : "收款人名称已经存在.",
	"DuplicateAccountNumber" : "Duplicate Account Number",
	"userNameExists" : "用户名称 (${0}) 已存在",
	"abbvNameExists" : "简称 (${0}) 已经存在",
	"reportNameExists" : "以这个名称命名的报告(${0}) 已经存在",
	"awbToolTip" : "此项是必填项",
	"requiredToolTip" : "此值是必填",
	"mandatoryBORefIDType" : "您必须选择一个BO参考号类型",
	"claimDateGreaterThanExpDateError" : "索赔日期 (${0}) 必须晚于或等于终止日期的 <br> (${1})。",
	"financeAmountLessThanPresentationAmount" : "融资金额 ${0} 必须小于提示金额 ${1}",
	"presentationAmountGreaterThanFinanceAmount" : "提示金额 ${0} 必须大于融资金额 ${1}",
	"invalidSpecialChargeCurrency" : "特别费货币必须与收费账户币种相一致。",
	"CIFFetcingmqFailure" : "提取CIF详细信息时，如出现技术性错误 <br> 请联系管理员。",
	"remittanceToolTip" : "此值是必填的。",
	"beneAccountCCValidationError" : "此受益人详细信息的结算代码不正确。",
	"noOfPayeeRef" : "票据参考号所有数字必须介于 1 和 5 之间。",
	"payeeRefExist" : "票据参考号(${0}) 已存在。",
	"yesMessage" : "是",
	"noMessage" : "否",
	"inputInMandatory" : "您必须在类型中选择一个输入",
	"invalidateRegistrationDialogText" : "您将修改已经作过登记的收款人。<br> 您要将关于此收款人的所有登记失效吗？<br>",
	"invalidAccountTypeProductType" : "找不到相应的账户说明以匹配。",
	"invalidBankCodeBranchCode" : "无效的银行代码/分支代码 ${0} / ${1}",
	"technicalErrorWhileValidatingBusinessDays" : "表格验证时出现技术错误。",
	"invalidIdNoFieldError" : "身份证号码必须含有三个数值 (国家, 类型, 号码)",
	"Authorizationlevelrequriederror" : "如果提供授权限额，授权级别需要提供",
	"submitAutoForwardTransactionConfirmation" : "您将自动发送日期及提交本交易。确定？",
	"submitAutoForwardMsg" : "自动发送及提交",
	"noTransactionsFound" : "没有找到的交易记录",
	"noTemplatesSelectedError" : "您必须至少选择一个模板",
	"invalidRegExpression" : "鉴于验证格式，该常规表达无效",
	"invalidAccountNumber" : "无效账户号码 ${0}",
	"accountValidationInterfaceError" : "由于服务器处理错误，账户验证失败。",
	"productCategoryMissing" : "产品类别中未找到账号{0}",
	"mqInterfaceFailure" : "验证受益人账号时${0}，出现技术错误。 <br> 请联系管理员。",
	"addBulkConfirmation" : "您将添加此交易至批量。确定？",
	"updateBulkConfirmation" : "您将更新批量中的本交易详情。确定？",
	"cancelBulkConfirmation" : "您将取消添加本交易至批量。确定？",
	"saveTemplateBulkConfirmation" : "您将添加本交易至批量模板中。确定？",
	"resubmitConfirmation" : "您将要重新提交此笔指令,确定是否继续?",
	"selectBeneficiaryCountry" : "您必须首先选择国家",
	"retrieveBulkDetailsError" : "更新批量详情时出错。批量总金额、 最高金额和交易记录计数可能不能反映实际值。",
	"fixBulkForwardDate" : "您所请求的转账日期是无效的。您想转发整包批量文件转账日期至${0}吗？<br/> <br/> 如果您单击确定，此包批量文件中的所有交易的转账日期将更新至新的日期，且此包批量文件将被提交。 <br/> <br/> 如果您单击取消， 此包批量文件的转账日期将不会被更改，且交易不会被提交。",
	"fixBulkResult" : "批量中的${0} 交易日期已被更新",
	"updateBulkError" : "批量更新时出错。不做任何更改。",
	"invalidCountryError" : "国家 ${0} 没有定义为一个有效的国家。",
	"removeFromBulkConfirmation" : "您将从批量交易中删除该记录 '${0}' <br>。确定？",
	"associatedCustomersMandatory" : "没有选定关联客户",
	"columnsMandatory" : "添加列",
	"debitAmountLessThanOutstandingAmount" : "借记金额 ${0} 必须小于未偿还总额 ${1}",
	"lcAmountLessThanELAmount" : "信用证金额 ${0} 必须小于出口信用证金额 ${1}",
	"lcAmountLessThanELAmountWithDiffCurr" : "信用证金额 ${0}${1} 必须小于出口信用证金额 ${2}${3}",
	"invalidFreqMessage" : "转让额度必须小于或等于 ${0}",
	"invalidStartDateMessage" : "开始日期必须介于{0} 和 ${1}",
	"customerMessage" : "请注意： 2月份重复出现的付款都将在该月的最后一天支付。",
	"CIFAlreadyAssignedtoOtherEntity" : "该CIF ${0} 已被分配至其他公司",
	"NoCIFFound" : "基于法律身份号、 类型和国家的特定组合，没有找到CIF号码",
	"NoAddressFound" : "未发现收费地址",
	"AddressFetcingmqFailure" : "获取地址详情 <br>时，出现技术错误。请联系管理员。",
	"submitRecurringPaymentTerminationConfirmation" : "您将终止此循环付款。",
	"submitPostDatedCancelConfirmation" : "您将取消该笔提前确定的跨期交易。确定？",
	"technicalErrorWhileConfiguringBeneficiaryAdvices" : "技术错误: 不能将受益人建议格式化。",
	"invalidCharacterPosition" : "无效字符的位置 '${0}'",
	"tokenAssign" : "用户安全密码器分配",
	"tokenModify" : "修改用户安全密码器",
	"tokenReplace" : "替换用户安全密码器",
	"tokenUnassign" : "取消分配用户安全密码器",
	"tokenAssignAction" : "分配用户安全密码器 ${0}",
	"tokenModifyAction" : "修改用户安全密码器 ${0}",
	"tokenReplaceAction" : "替换用户安全译码器 ${0}",
	"tokenUnassignAction" : "取消分配用户安全密码器",
	"tokenAssignType1" : "-系统分配 (银行汇总)",
	"tokenAssignType2" : "-手动分配 (银行汇总)",
	"tokenAssignType3" : "-手动分配 (机构汇总)",
	"tokenAssignType4" : "-私人译码器",
	"tokenModifyPrivatize" : "-私人安全密码器设置",
	"systemSerialNoMsg" : "经批准后派发",
	"FXDefaultErrorMessage" : "您输入的是无效的外汇。请更正您的输入。",
	"FXTranAmtGreaterThanBillAmtMessage" : "交易金额应小于或等于单据金额。",
	"FXUtiliseAmtGreaterMessage" : "可供使用的总金额应小于或等于交易金额。",
	"FXAmountNotInSpecifiedRange" : "若要访问此选项，您的交易金额必须介于 ${0} ${2} 和 {1} ${2}之间。",
	"FXOptionNotAvailable" : "您没有访问此外汇选项。",
	"selectBankToProceed" : "选择银行以继续",
	"selectEntityToProceed" : "选择公司身份认证以继续",
	"beneAdvChangingTemplateFormat" : "更改模板格式将清除以前的格式的数据！",
	"beneAdvClearAll" : "所有在受益人建议中的输入值都将被清除。您要继续吗？",
	"beneAdvMaxRowsReached" : "已达到最大行数!",
	"FAClientAvailTitleMessage" : "查看可获得的客户信息",
	"FAClientExpoTitleMessage" : "查看敞口查询",
	"uploadTemplateDelimiterRequired" : "选择分隔符",
	"uploadTemplateDelimiterTextRequired" : "输入分隔符文本",
	"selectAllUploadTemplateKeyColumns" : "要选择所有关键列",
	"selectPaymentTerm" : "您可以选择 '付款条目 >货币种类 '及'付款条目>金额'或'付款条目 > 百分比'",
	"uploadTemplateValueRequired" : "此值是必填的",
	"otpEntityMandatory" : "公司代码是必填的",
	"securityTokenGenerate" : "放弃的安全密码器号码不能大于生成的号码",
	"mandatoryEntMessage" : "公司代码是必填的",
	"mandatoryAcctNumberMessage" : "账户号是必填的",
	"mandatoryChqNumberMessage" : "支票号是必填的",
	"mandatoryChqNumberValMessage" : "“至支票号”应大于“从支票号”的值",
	"mandatoryChqNumberRangeValMessage" : "“从”和“至”支票号是超出范围 [${0}]。<br>最多可以询问 ${1} 支票",
	"mandatoryStopChqNumberRangeValMessage" : "“从”和“至”支票号码是超出范围 [${0}]。<br>最多可以请求停止 ${1} 支票",
	"ChequeNumberFromNonZeroValMessage" : "“从支票号”不应为 0",
	"minChqBooksRequest" : "您必须要求一份最小${0} 支票簿",
	"maxChqBooksRequest" : "您可以请求一份最大${0} 支票簿",
	"minMaxChqBooksRequestConfigMissing" : "支票书最低，最大请求配置丢失。<br> 请联系银行管理员。",
	"beneAdvTemplateModifiedAlert" : "很抱歉。受益人回单模板格式已被修改。请重新输入详细信息。",
	"beneAdvAtleastOneDeliveryModeRequired" : "请至少选择一个模式传送受益人回单",
	"resetInvoicePayableCurrency" : "更改发票币种。您是否想要删除所有条目？",
	"maxFileUploadReached" : "达到最大上传文件量",
	"autoForwardMultipleSubmission": "您是否要将此交易自动展期?",
	"failedSingleSubmissionFromDraft": "对不起,转帐日期为过去或已超过截止时间.请重新选择有效日期.",
	"failedMultipleSubmission": "以下交易的转帐日期无效",
	"failedMultipleSubmissionCutOff": "对不起,以下交易已超过截止时间.",
	"failedMultipleSubmissionHoliday": "对不起,以下交易的转帐日期为非工作日.",
	"securityToken" : "请输入有效的安全密码器号码",
	"otpLegalInfoMandatory" : "必须为合法信息。",
	"privateTokenValidationFailed" : "无效的安全密码器号码或与所提供的合法信息不相匹配的安全密码器号码",
	"tokenValidationFailed" : "无效的安全密码器号码或无法用于分配的安全密码器",
	"selectEntityForFileUpload" : "请选择公司代码",
	"bulkPaymentsProductGroup" : "付款",
	"bulkCollectionProductGroup" : "托收",
	"bulkPayrollProductGroup" : "工资",
	"mandatoryFieldsToOkError" : "所有字段都必须处于有效状态才能<br> 提交对话框的。",
	"mandatoryValidateTokenOkError" : "继续前，请首先按验证按钮。",
	"submitTransactionConfirmationWithMargin" : "本银行保函将在有保证金前提下发行。<br> 您将尝试提交输入数据。确定？",
	"msgActiveStatusToMarkPrivateError" : "安全密码器状态将被激活以标志为专属的安全密码器",
	"msgActiveStatusPriorMarkPrivateError" : "在标记作密码器为私人密码器前密码器的状态必须激活。",
	"atleastOneTransactionHasTobeAddedForBulk" : "至少一个交易记录必须添加至批量中",
	"oneTransactionIsInvalid" : "所有交易必须在有效状态",
	"debitAmtLessThanDocumentAmt" : "借方金额 ${0} 必须小于或等于合约中金额 ${1}",
	"settlementAmtLessThanTnxAmt" : "清算金额 ${0} 必须小于或者等于交易金额 ${1}",
	"batchTransactionsError" : "批处理的标准错误： 请选择同一货币、 公司 ID、 状态的交易。其中无 <br>任何交易已进行批处理 ！",
	"submitBatchConfirmationWithCurrencyLimit" : " 您将提交 <br> 批处理中的所有交易。确定？ <br> <font color= 'red'> 大额交易提醒：贵帐户非柜面转帐单日累计金额已接近/超过人民币100万元。请确认本次付款。 </font>",
	"deleteBatchConfirmation" : "您将删除当前的 <br> 批处理的详细信息。确定？",
	"submitBatchConfirmation" : "您将提交 <br> 批处理中的所有交易。确定？",
	"selectAtleastOneTnxToMove" : "至少有一笔交易已被选中移至其他批量。",
	"confirmForDeMergeBulk" : "您确定要将以下参考号的交易移至所选的批量${0}'吗？",
	"confirmForDeMergeBulkForNewBulk" : "您确定要将以下参考号的交易移至新批量${0}'吗？",
	"batchSelectedDelete" : "您确定要删除所选的批量处理吗？",
	"beneAdvColumnExists" : "与此标签的列已存在 ！",
	"invalidExchangeAndTolerateRateLength" : "无效的汇率和容差率。允许的长度 4n.7n",
	"invalidExchangeAndTolerateRate" : "无效的汇率和容差率。",
	"invalidAmountValueError" : "金额不能小于零。",
	"invalidMinAmountValueError" : "最低金额不能大于最大金额。",
	"invalidMaxAmountValueError" : "最大金额不能低于最低金额。",
	"generateEsignRequest" : "您将生成电子签名请求 ！",
	"proxyAuthorise" : "您将代理批准本次交易！",
	"sendEsignRequestConfirm" : "您将发送电子签名要求。确定？",
	"selectAuthoriserError" : "请选择批准者！",
	"selectRequestModeError" : "请选择请求模式 (短信或电子邮件) ！",
	"inputOTPResponseError" : "请输入您的 一次性密码 ！",
	"proxyAuthoriseTransaction" : "你输入一次性密码代理批准。确定？",
	"invalidTotalWidthOfSelectedColumns" : "所选的列的总宽度应小于或等于 100",
	"invalidPhraseTextError" : "内容不应超过 2000个字符。",
	"entitynotselected" : "首先选择公司代码。如果未选择公司代码，则不能选择账户",
	"swiftValidationFailed" : "Swift BIC ${0} 不可用。当输入 BIC 代码时，代码必须从查找中获得。",
	"confirmDeletionGridRecord" : "您正在删除记录，请确认",
	"beneficiaryName" : "从第一行向下，请输入该受益人名称字段。",
	"errorAccountCheckDigit" : "账号位数检查失败。",
	"bankCodeBranchCodeRequiredMessage" : "请输入银行代码和分行代码以验证账号。",
	"invalidIBGAccount" : "基于银行代码 ${1} 和分支代码 ${2} 组合的无效账户 ${0}",
	"accountInputError" : "本次输入不允许作为可供选择或输入的唯一账号。",
	"LastModifiedDateFromLesserThanLastModifiedDateTo" : "从上次修改日期必须早于或等于上次修改日期至 <br>",
	"LastModifiedDateToGreaterThanLastModifiedDateFrom" : "上次修改日期至必须晚于或等于 <br> 从上次修改日期",
	"LastModifiedDateGreaterThanCurrentDate" : "最后修改日期 从 必须晚于或者等于  <br> 当前日期",
	"transferDateGreaterThanCurrentDateError" : "从转让期 ${0} 必须晚于或等于至当前日期的 <br>",
	"endDateGreaterThanCurrentDateError" : "结束日期 ${0} 必须晚于等于 <br>现在日期",
	"processingDateGreaterThanCurrentDateError" : "处理日期 ${0} 必须晚于或等于至当前日期的 <br>",
	"totalamount" : "此值超出范围。",
	"startDateGreaterThanCurrentDateError" : "开始日期 ${0} 必须晚于或等于至当前日期 <br>",
	"invalidLocalCurrencyError" : "货币 ${0} 不允许用于银行 Giro(Express) 转让。",
	"recurringOnRequired" : "选择再次出现。",
	"ListOfAccountsTitleMessage" : "账户的列表",
	"ListOfBeneficiriesTitleMessage" : "受益人名单",
	"ListOfSwiftBanksTitleMessage" : "swift银行名单",
	"ListOfBanksTitleMessage" : "银行名单",
	"clearingCodeFormatMessage" : "格式： ${0} <br> 验证： ${1}",
	"beneAccountCCValidationMandatoryError" : "必须输入受益人信息的清算代码",
	"beneAccountCCValidationNoRequiredError" : "不需要输入受益人信息的清算代码。请从字段中删除。",
	"invalidRegularExpressionError" : "清算代码说明 ${0}的无效常规表达。<br> 请联系技术支持。",
	"beneAccountCCValidationPrefixStartsWithError" : "受益人账号无效。清除代码 ${0} 应从清算代码前缀 ${1}开始。",
	"CCValidationUnmatchedPrefixError" : "清算代码前缀不适用所选的清算代码说明。",
	"beneAccountCCValidationUnsupportedClearingCodeError" : "清算代码不支持受益人账户国和汇款币种",
	"CCValidationInvalidClearingCodeDescriptionError" : "请提交结算代码和描述信息。 <br> 任何信息正丢失。",
	"technicalErrorWhileInterestRateFetch" : "重新取回利率时出现技术错误<br> 请您联系管理员。",
	"technicalErrorReauth" : "重新身份验证时出现技术。<br> 请联系管理员。",
	"technicalErrorTnxConfirmationDetails" : "在提取确认细节时，发生一个技术错误. <br> 请联系您的管理员.",
	"accountStatementErrorToolTip" : "此值是必填",
	"maxBillReferenceReached" : "已达到条例引用的最大值",
	"acceptTermsAndConditions" : "请选择我同意条款和条件，然后单击确定按钮",
	"invalidInsuranceBorneBy" : "该选项不适用于Incoterm",
	"invalidAuthorisationRole" : "${0} 作用类型不是有效的 ${1} 作用目标。",
	"role" : "角色",
	"authLevel" : "授权级别",
	"fxToleranceRangeError" : "容差率应介于 ${0} 和 ${1}之间。",
	"fxContractUtlizeAmtError" : "使用的总金额 ${0} 应该小于或等于交易金额 ${1}",
	"fxContractMustBeEqualError" : "使用${ 0 }总量应该等于交易金额${ 1 }",
	"helpQuantityCodesDialogTitle" : "代码数量",
	"helpPaymentTermCodesDialogTitle" : "付款方式编码",
	"Lost" : "丢失",
	"Damaged" : "损坏",
	"Activated" : "激活",
	"Frozen" : "故障",
	"Deleted" : "删除",
	"Moved" : "移动",
	"invalidCurrency" : "货币无效",
	"attachementFileMandatoryError" : "您必须附加文件 <br>以提交交易记录。",
	"noBeneficiaryEmail" : "对于此收款人没有预先设置的邮件或者收款人没有输入.<br>请另外提供一个邮件.",
	"selectDebitFirst" : "您必须选择一个借记账户",
	"confirmDeletionCustomerReferenceRecord" : "您要删除客户参考记录. 请确认?",
	"confirmDeletionAccountRecord" : "您将要删除帐户记录，是否继续?",
	"duplicateCustomerReference" : "客户参考不能重复.客户参考${0} 已经存在.",
	"FinAmtGreaterThanBillAmtValidation" : "融资金额不能大于票面金额.",
	"duplicateAccountNumber" : "账号不能重复  账号 ${0} 已经存在 ${1}.",
	"duplicateColumnName" : "不能有重复的栏位. 这个栏位已经被添加.",
	"accountDetailsTitle" : "账户细节",
	"additionalPostingDetailsTitle" : "额外过账细节",
	"amountcannotzero" : "金额不能为零.",
	"drawdownamountvalidation" : "亏损应该小于或者等于货币金额",
	"paymentsplitvalidation" : "分期付款应当少于或者等于货币金额",
	"transferAmountEmptyZero" : "转账分配金额不能为 '0'(零) 或空",
	"invalidMessage" : "输入的值无效.",
	"new" : "新建",
	"amend" : "修改",
	"reporting" : "报告",
	"message" : "消息",
	"invalidMaxUploadSize" : "上传文件最大不能超过 ${0} MB",
	"detachedBankHasCustRef" : "现有客户参考将被删除",
	"eligibleForFinancing" : "允许融资",
	"notEligibleForFinancing" : "不允许融资",
	"fscm_programme_01" : "提前付款计划",
	"fscm_programme_04" : "核准的应付帐款融资计划",
	"errorInvoiceElgibleAmountGreaterThanInvoiceAmount" : "发票合格金额不能大于发票金额.",
	"errorFinanceAmountGreaterThanInvoiceAmount" : "融资金额不能大于发票金额.",
	"errorFinanceAmountGreaterThanInvoiceEligibleAmount" : "融资金额不能超过发票金额.",
	"errorSelectCounterpartyCollaboration" : "请首先选择一个对手方.",
	"errorCounterpartyCollaborationNotEnabled" : "选择的对手方没有启用合作.",
	"errorPaymentAmountGreaterThanInvoiceAmount" : "付款金额不能大于发票金额.",
	"errorPaymentAmountGreaterThanInvoiceEligibleAmount" : "付款金额不能大于发票金额.",
	"inValidCustomerReference" : "开立参考不能为空",
	"amountOrPercentageReq" : "输入义务支付金额或者百分比.",
	//Beneficiary Related localizations
	"invalidBeneficiaryName" : "无效的收款人名称.",
	"invalidBeneficiaryAddressField" : "无效的地址条目.",
	"invalidContent" : "无效的内容",
	"employeeNoExists" : "员工号码 (${0}) 已经存在",
	"unsavedData" : "页面包含未保存的数据,这些数据会丢失.",
	"unsavedDataPreUnload" : "是否保存",
	"asyncMessage" : "交易信息",
	"asyncSaveError" : "交易无法保存",
	// Trade Rolling Renewal date related localizations
	"expiryDateReqdForFinExpiryDateError" : "到期日必须填写如果到期续约",
	"calendarDateReqdForFinExpiryDateError" : "如果需要展期，展期日期必须填写",
	"renewOnNotSelectedError" : "更新是必须的",
	"finExpiryDateLessThanLastActiveDateError" : "最后到期日 (${0}) 必须晚于或者等于 (${1})",
	"nbofRenewalsNotSelectedError" : "展期的数量' 需要填写",
	"renewForNotSelectedError" : "展期' for 必须",
	"calendarDateLessThanSystemDate" : "选择的日期必须晚于系统日期 (${0}) 并且早于或者等于有效日期 (${1})",
	"expiryDateReqd" : "必须输入有效日",
	"incorrectPercentage" : "输入无效,请输入正确的百分比",
	"emptyPercentage" : "要求的百分比为空,请输入正确金额.",
	"valueShouldBeGreaterThanZero" : "您输入的值无效. 请输入大于0的值.",
	"selectFSCMProgrammeFirst" : "您必须首先选择一个FSCM 程序.",
	"canNotMoreThanTranAmt" : "未清偿金额不能大于银行担保金额, 请改正.",
	"selectReleaseFull" : "选择 '全部释放' 表示释放金额等于所有未偿金额",
	"duplicateEntity" : "已经有相同机构添加入报表.",
	"addAColumnFirst" : "请首先增加栏位.",
	"decAmountLessThanOutstandingAmt" : "减少的金额应当少于等于未偿还金额 (${0} ${1}).",
	"lineItemNetAmountOutOfRange" : "列出条目总金额超过长度限制.",
	"ListOfInvoicesTitleMessage" : "发票列表",
	"claimAmtGreaterThanOutstandingAmtError" : "申请金额不能大于未清偿金额 (${0}). 金额也不能大于零.",
	"claimDateGreaterThanCurrentDateError" : "索赔日期(${0}) 必须早于或者等于 <br> 现有系统日期 (${1}).",
	"claimDateGreaterThanExpiryDateError" : "申请日期 (${0})应当早于 <br>交易到期日期 (${1}).",
	"claimDateLessThanIssueDateError" : "申领日期 (${0}) 必须早于 <br>交易发生日期 (${1}).",
	"claimReferenceExists" : "申请参考 (${0}) 已经存在.",
	"tnxAmtGreaterThanClaimAmtError" : "交易金额 (${0}) 不能大于名义金额 (${1}).",
	"tnxAmtZeroError" : "交易金额不能为零.",
	"selectAtleastOneFileForFileAct" : "请至少选择一个文件 for FileAct!",
	"invoicesSumLessThanCNAmount" : "发票总金额必须少于或者等于贷款通知金额.",
	"settlementAmountLessThanOutstandingAmount" : "发票结算金额应小于或等于发票未清金额.",
	"dayInMonthNotApplicableForDaysError" : "天月是不允许频率单位为天",
	"projectedExpDateLessThanTransactionExpDtError" : "预计有效日期 (${0}) 不能早于交易失效日期 (${1})",
	"projectedExpDateGreaterThanFinalExpDtError" : "预计到期日 (${0}) 不能晚于最终到期日 (${1})",
	"finalExpDateLessThanTransactionExpDtError" : "最终到期日 (${0}) 不能早于交易到期日(${1})",
	"finalExpDateLessThanProjectedExpDtError" : "最终到期日(${0}) 不能早于预计的到期日 (${1})",
	"poReferenceExists" : "订单参考 (${0}) 已经存在.",
	"poReferenceSelectBuyer&Seller" : "请首先选择买家细节以及卖家细节.",
	"resetPurchaseOrderCurrency" : "新订单的币种适用于所有已经存在的条目.",
	"resetImportOpenAccountCurrency" : "新进口赊账币种适用于所有已经存在的条目.",
	"resetExportOpenAccountCurrency" : "新的出口赊账贸易币种必须适用于所有已经存在的额度条目.",
	"cnReferenceExists" : "贷记提示参考 (${0}) 已经存在.",
	"contactEitherBuyerbankOrSellerbank" : "您可以选择增加卖方银行联系人或者买方银行联系人.",
	"bpoAmountGreaterThanTotalAmtError" : "银行义务付款金额应当小于总净额.",
	"entityValidationError" : "超过一个或者多个额度使用此机构,因此不能被删除.",
	"limitDateError" : "限额重审日期不能晚于额度重审日期",
	"reviewDateError" : "比起现有选择的日期，超过一个或者多个额度需要审批.(TBD)",
	"facilityReviewDateMissing" : "增加额度之前,请先输入审查日期",
	"facilityEntitySelectListMissing" : "请在增加额度之前选择机构",
	"facilityCurAmountMissing" : "请为此额度输入币种和金额细节.",
	"limitDateSmallerThanCurrentDate" : "审查时间不能早于现有时间.",
	"deleteLimitsOnRefChange" : "修改客户参考将导致所有额度删除. 您确认是否继续?",
	"deleteLimitsOnAbbvNameChange" : "修改银行简称会删除所有额度. 您是否继续?",
	"facilityRefExists" : "额度参考 (${0}) 已经存在",
	"LimitRefExists" : "额度参考已经存在",
	"limitDefinitionIncomplete" : "请在所有必输项内填上内容",
	"limitDuplicationError" : "额度定义已经存在",
	"addLimitValidationWE" : "请在所有必输项内填入相关内容",
	"addLimitValidationWOE" : "请在所有必输项内填入内容",
	"totalLimitAmountError" : "额度总合超过融资总额",
	"invalidBookingTnxAmount" : "录入金额大于交易金额",
	"inValidEntitesForTemplate" : "机构 (${0}) 不输入产品模版 (${1})",
	"facilityAmountDecreaseError" : "金额不能减少",
	"invalidBookingAmountCurrency" : "录入金额超过 ${0} 可用金额. 适用货币转换 ${1}",
	"invalidBookingAmount" : "录入金额大于 ${0} 可用金额",
	"amendLimitDateExpiry" : "额度已经过期. 交易不能被提交",
	"duplicateBicIdImportOpenAccount" : "发现重复的BIC 码",
	"BpoSumMoreThanIoAmount" : "银行总义务付款金额不能超过进口赊账金额.",
	// Treasury account
	"Owner_Type_01" : "客户",
	"Owner_Type_10" : "司库",
	"emptyOpicsPlusCustId" : "清在司库客户ID  域内输入一个 值",
	"numericCustId" : "请输入一个数字",
	"emptyField" : "域为空",
	"lengthTreasuryCustomerField" : "财务客户ID 不能超过10位",
	"invalidCustomerReference" : "无效的客户参考",

	// License related localizations - Start
	"exporter" : "出口商",
	"consignee" : "收货人",
	"applicant" : "申请人",
	"beneficiary" : "收款人",
	"payer" : "付款人",
	"payee" : "收款人",
	"lsNameExists" : "许可证名称 (${0}) 已经存在.",
	"validFromDateLessThanAppDateError" : "有效日期从 (${0}) 必须晚于或者等于 <br>申请日期 (${1}).",
	"validFromDateLessThanRegDateError" : "有效日期从 (${0}) 必须晚于或者等于 <br>注册日期 (${1}).",
	"validFromDateLessThanIssDateError" : "有效日期从 (${0}) 必须晚于或者等于 <br>签发日期(${1}).",
	"validFromDateGreaterThanLatestPaymntDateError" : "有效日期从 (${0}) 必须早于或者等于 <br>最近付款日期 (${1}).",
	"validToDateLessThanAppDateError" : "有效日期 (${0}) 必须晚于或者等于 <br>申请日期 (${1}).",
	"validToDateLessThanTodayDateError" : "有效日期 (${0}) 必须晚于或者等于<br>现在日期.",
	"validToDateLessThanIssDateError" : "有效日期 (${0}) 必须晚于等于 <br>签发日期 (${1}).",
	"validToDateLessThanValidFromDateError" : "到期日结束 (${0}) 必须晚于或者等于 <br>到期日开始 (${1}).",
	"validToDateGreaterThanLatestPaymntDateError" : "有效日期 (${0}) 必须早于或者等于 <br> 最后付款日期 (${1}).",
	"latestPaymentDateLessThanAppDateError" : "最后付款日期 (${0})必须晚于或者等于 <br>申请日期 (${1}).",
	"latestPaymentDateLessThanIssDateError" : "最近付款日期 (${0}) 必须晚于或者等于 <br> 签发日期 (${1}).",
	"latestPaymentDateLessThanValidFromDateError" : "最近付款日期 (${0}) 必须晚于或者等于 <br> 额度启用时间 (${1}).",
	"latestPaymentDateLessThanValidToDateError" : "最近付款日期 (${0}) 必须晚于或者等于 <br>有效日期 (${1}).",
	"issueDateGreaterThanValidFromDateError" : "签发日期 (${0}) 必须小于或者等于 <br> 有效日期 (${1}).",
	"issueDateGreaterThanCurrentDateError" : "签发日期(${0}) 必须小于或者等于 <br>现有日期.",
	"regDateGreaterThanIssDateError" : "The Registration Date (${0}) must be less than or equal <br>to the Issue Date (${1}).",
	"issDateLessThanRegDateError" : "签发日期 (${0}) 必须晚于或者等于 <br>注册日期 (${1}).",
	"issueDateGreaterThanValidToDateError" : "签发日期(${0}) 必须早于或者等于 <br>有效日期 (${1}).",
	"issueDateGreaterThanLatestPaymentDateError" : "签发日期 (${0}) 必须早于或者等于 <br>最近付款日期 (${1}).",
	"licenseLiabilityAmountCanNotBeGreaterThanLicenseTotalAmount" : "未偿还金额不能大于授权总金额,请更正.",
	"cannotDecreaseMoreThanLiabilityAmount" : "总金额减少的额度不能大于未清偿金额 (${0}).",
	"invalidLSTotalAmtError" : "无效的总许可金额. 总许可金额不能为零.",
	"invalidLSDescGoodsLength" : "物品描述不能超过35个字符.",
	// License related localizations - End
	"singleHyphenError" : "这个栏位不能只有一个横杠",
	"selectInstructionError" : "请选择客户/银行付款指令",
	"paymentDateSmallerThanSystemDate" : "还款日期 (${0})必须晚于系统日期.",
	"paymentAmtGreaterThanLiabAmtError" : "还款金额不能超过原始负债金额.",
	"attachOneInstruction" : "在提交之前,至少需要附上一个指令.",
	"attachFreeFormatInstruction" :  "Please choose Free Format instructions for bank payment, as Bank Standing instructions are not available",
	"selectBuyerBank" : "请首先选择买家所在银行.",
	"alertDeleteBuyerBankRow" : "买家银行业务如果存在将得到更新. 在提交之前请审查银行相关义务.",
	"totalSettlementAmtGreaterThanOSAmtError" : "结算总额(${ 0 })不能超过许可债务总额(${ 1 })",
	"lsSettlementAmtGreaterThanLSAmtError" : "许可清算金额(${0}) 不能大于许可金额(${1}).",
	"addSettlementAmtGreaterThanAddAmtError" : "额外的结算金额${0}) 不能超过额外的许可金额(${1}).",
	"lsAmtGreaterThanMasterLSAmtError" : "许可金额(${0}) 在清算时候不能大于主金额(${1}).",
	"lsAddAmtGreaterThanMasterLSAddAmtError" : "额外许可金额(${0}) 涉及到清算, 不能大于在主合同的金额(${1}).",
	"startDateLessThanDateOfDayError" : "开始日期 (${0}) 必须晚于或者等于 <br>今天 (${1}).",
	"requestDateLessThanDateOfDayError" : "要求日期 (${0}) 必须晚于或者等于 <br>今天 (${1}).",
	"errorFXOverDraftAccountRecordNotFound" : "透支账户记录未找到.",
	"errorDAccountnotfound" : "没有找到DAccount",
	"errorDeadLineOfPayment" : "当天付款的申请已经超过截止时间，请联系你的 FX Advisor.",
	"debitAccountNotSelected" : "请先选择借记账户.",
	"debitAccountDifferentFromCreditAccount" : "借记金额必须和贷记金额不同.<br>两个账户不能相同.",
	"EffectiveDateFromLesserThanEffectiveDateTo" : "有效起始日期' 必须早于或者等于 <br> '有效结束日期'",
	"EffDateToLessThanCurrentAndGtrThanEffDateFrom" : "有效日期到必须早于当前日期 <br> 晚于有效日期从",
	"DueDateFromLesserThanDueDateTo" : "到期日开始必须早于或者等于 <br>到期日结束",
	"DueDateToGreaterThanDueDateFrom" : "到期日到必须晚于或者等于 <br> 到期日从",
	"errorAccountOrPaymentInformationMissing" : "借计金额贷计金额或者付款信息缺失.",
	"mustChooseInstructionsType" : "您必须首选选择一笔交易类型.",
	"ListOfLicensesTitleMessage" : "许可证列表",
	"selectRequiredValuesFirst" : "您必须首先选择到期日, 申请人, 受益人和交易币种.",
	"selectRequiredValuesFirstForEL" : "您必须首先选择有效日期, 收款人以及交易币种.",
	"selectRequiredValuesFirstforCollections" : "您必须首先选择开票人,受票人交易币种.",
	"licensesSumGreaterThanTnxAmountError" : "已分配的总许可金额必须等于交易金额.",
	"noLicenseAmountError" : "已经使用的许可金额不能为空. 金额必须被使用因为许可已经被连接",
	"allocatedAmtGreaterThanAvailableLSAmtError" : "分配的许可金额不能大于可用许可金额.",
	"licenseValueZeroError" : "许可额度不能为零.",
	/*"allocatedAddAmtGreaterThanAvailableLSAddAmtError" : "Allocated Additional License Amount cannot be greater than the Available Additional License Amount.",*/
	"multipleLicenseSelectionNotAllowedError" : "多种许可不能被选择. 一个或者多个可选择的许可交易没有多重优先选择权.",
	"selectInstructionsError" : "请选择银行付款指令.",
	"maturityDateLessThanDateOfDayError" : "到期日 (${0}) 必须晚于或者等于 <br>今天(${1}).",
	"startDateGreaterThanMaturityDateError" : "开始日期 (${0}) 必须小于或者等于 <br>到期日 (${1}).",
	"maturityDateSmallerThanStartDateError" : "到期日(${ 1 })必须大于或等于开始日期< br >(${ 0 })",
	"repricingFromGreaterThanRepricingTo" : "重新定价日期从必须早于或者等于<br> 重新定价日期到",
	"repricingToLesserThanRepricingFrom" : "重新定价日期到必须大于或者等于 <br> 重新定价日期从",
	"repricingBatchTransactionsError" : "重新定价字段错误 : 请选择具有同样借款人ID, 交易名称币种以及重新定价日期的贷款!",
	"invalidNumberOfRollingRenewals" : "滚动展期应当大于 1.",
	"errorTDRejected" : "您的请求不能被处理.<br>您的请求不能被处理.",
	"resetLicenseGrid" : "对应的许可将被解挂, 是否继续?",
	"linkedLoanDeleteAction" : "您将要把此笔贷款 ${0} 和这笔价格重估交易取消关联!",
	"lastLoanInlinkedLoanDeleteAction" : "您不能脱钩此贷款 ${0}因为这是最后一笔针对重新计价交易连接的贷款!",
	"decreaseAmtCannotMoreThanRolloverAmt" : "减少的金额不能大于展期金额.",
	"rollOverAmtCannotbeZero" : "展期金额不能为零.",
	"decreaseAmtCannotbeZero" : "减少金额不能为0 .",
	"increaseAmtCannotbeZero" : "增加金额不能为零.",
	"enterRenewalDetails" : "在附上许可之前, 您必须在展期部分输入最后到期日.",
	"dynamicTextEmptyError" : "您必须添加相应的内容",
	"expDateSmallerThanCurrentDate" : "到期日 (${0}) 必须晚于现有日期.",
	"bothWeeklyHolidaySameError" : "每周一次的假期不能相同.",
	"InvoiceIssueDateFromLesserThanInvoiceIssueDateTo" : "发票签发日期从必须早于或者等于 <br>发票签发日期到",
	"InvoiceIssueDateToGreaterThanInvoiceIssueDateFrom" : "发票签发日期到必须晚于或者等于 <br> 发票签发日期从",
	"InvoiceDueDateFromGreaterThanInvoiceDueDateTo" : "发票到期日期从必须早于或者等于 <br> 发票到期日期到",
	"InvoiceDueDateToLesserThanInvoiceDueDateFrom" : "发票到期日到必须晚于或者等于 <br>发票到期日从",
	"financeRequestAmtErrorForIntentPayAmt" : "申请融资金额应当小于或者等于支付金额",
	"financeRequestAmtErrorForTotalAmt" : "融资需求金额应当小于或者等于总计金额",
	"financeRequestAmtError" : "请求融资金额必须大于零",
	"closingDateLessThanCurrentDateError" : "期末日期(${0}) 必须大于现有日期.",
	"batchDateGreaterThanCurrentDateError" : "批量打包日期必须早于等于当前日期.",
	"addAmtOrRate" : "你必须输入金额或者利率.",
	"addLabelOrInfo" : "您必须输入标签或者信息.",
	"addAmtOrPercentage" : "您必须输入金额或者百分比.",
	"dayInMonthZeroNotApplicableError" : "零不能用于在月天数.",
	"outstandingAmountZeroError" : "未清偿额必须大于零.",
	"settlementAmountGreaterThanOutstanding" : "交易金额必须小于或者等于未清偿金额.",
	"selectFreeFormatInstructionsError" : "请选择自由格式指令.",
	"rollingFrequencyCannotBeMoreThanRenewalPeriodError" : "展期频率必须少于或者等于更新周期.",
	"mandatoryFieldsAndInstructionsRequired" : "所有必输项内填入内容.",
	"accountNumber" : "账户",
	"accountOwnerType" : "账户所有者类型",
	"accountType" : "账户类型",
	"accountProductType" : "账户产品类别",
	"accountCcy" : "币种",
	"accountDescription" : "描述",
	"custAccountType" : "客户账户类型",
	"bankId" : "Bank ID",
	"branchNo" : "分行代码",
	"nra" : "NRA",
	"custReference" : "客户参考",
	"mandatoryFieldsInvalidStateError" : "所有必输域必须为有效状态.",
	"reportOverAllAggregateError" : "Sorry, please remove added aggregates as this report is eligible to create a chart",
	"active" : "激活",
	"noDealsDataFound" : "对于指定借款人参考未发现任何数据, 请尝试选择不同借款人参考.",
	"loanBorrowerReferenceDefault" : "错误",
	"invalidContentHttps" : "å†…å®¹æ— æ•ˆ. å†…å®¹åº”è¯¥èµ·å§‹äºŽ http:// æˆ– https://",
	"outstandingAmountShouldBeGraterThanLCAmount" : "Outstanding Amount Should Be Grater Than LC Amount",
	"decreaseAmountShouldBeLessThanLCAmount" : "Decrease Amendment Amount Should Be Less Than LC Amount",
	"emailIdEmpty" : "对不起,您没有设置公司联系人电邮",  
	"column" : "Column",
	"operator" : "Operator",
	"value" : "Value",
	"reportChartYAxisMandatory" : "Y Axis for chart is mandatory",
	"ZeroLinesPerPageNotApplicableError" : "Number of lines per page must be greater than zero.",
	"DecimalNotAllowedError" : "Decimal values or alphabets not allowed.",
	"warningMsgAmendLC" : "Amendments awaiting Beneficiary response exists. Continue?",
	"Role(s)" : "角色（S）",
	"beneficiaryIsInactive" : "受益人主人不活跃，请在提交交易之前更改受益人。" ,
	"expiryDateMandatoryError" : "The Expiry Date must be selected for Discount." ,
    "selectExpiryDateError": "The Expiry Date must be greater than Current Date.",
    "expiryDateGraterThanDueDateError" : "The Expiry Date (${0}) must be less than the Due Date (${1}).",
    "cptyAbbvNameFormatError" : "缩写名称应仅包含字母数字字符。",
    "selectAdjustmentExpiry" : "您可以选择“总调整”和“折扣过期日期”或“无”",
    "mismatchFrom" : "The transfer from currency should be the same as to currency",
    "mismatchFromINR" : "Please select the valid Currency, Only INR allowed for India Domestic Payments",
    "EmptyAccountError": "请选择要导出的帐户",
    "MT940ExportError" : "MT940无法导出超过1天或当天的声明",
    "ExternalAccountError" : "不允许MT941和MT942导出外部帐户",
    "MT941942ExportError" : "MT941和MT942只能分别输出当日余额和对帐单",
    "invalidCNAPSBankCode" : "无效的CNAPS银行代码",
    "bulkCNYError" : "Please select the valid Currency, Only CNY allowed for CNAPS Payments",
    "settlementamtlessCNAmt" : "Settlement amount is less than the Credit Note Amount. Please submit again to continue.",
    "documentattachedMustError" :"You must define at least one document.",
    "addressLine4ToolTip" : "Since Address Line 4 has been used the mode of transmission will be other than SWIFT, else to adhere to SWIFT standards input only in Address Line 1, 2 and 3.",
    "selectEntityBeforeBank" : "Please select entity first.",
    "disposalInstruction" : "Please provide your disposal instruction",
    "submitMigrateAllTransactionsConfirmation" :"You are going to Migrate the Transaction for the Product Code ${0} and Company ${1}. <br>Are you sure?",
	"submitMigrattionSuccess" : "The Migration completed for the Product Code ${0} and Company ${1}. <br>Please check the Log for more details.",

	// Cash Pooling
	"cashPoolingbalanceGroupHeaderCode" : "Code",
	"cashPoolingbalanceGroupHeaderDescription" : "Description",
	"cashPoolingbalanceGroupHeaderFrequency" : "Frequency",
	"cashPoolingbalanceGroupHeaderBalanceType" : "Balance Type",
	"cashPoolingbalanceGroupHeaderCurrency" : "Currency",
	"cashPoolingbalanceGroupHeaderMinimum" : "Minimum",
	"cashPoolingbalanceGroupHeaderRounding" : "Rounding",
	"cashPoolingbalanceGroupHeaderOrder" : "Order",

	"cashPoolingbalanceSubGroupHeaderCode" : "Code",
	"cashPoolingbalanceSubGroupHeaderDescription" : "Description",
	"cashPoolingbalanceSubGroupHeaderPivot" : "Pivot",
	"cashPoolingbalanceSubGroupHeaderType" : "Type",
	"cashPoolingbalanceSubGroupHeaderBalanceTarget" : "Balance Target",
	"cashPoolingbalanceSubGroupHeaderBalanceLowTarget" : "Balance Low Target",
	"cashPoolingbalanceSubGroupHeaderBalanceMaxTarget" : "Balance Max Target",
	"cashPoolingbalanceSubGroupHeaderLowTarget" : "Low Target",
	"cashPoolingbalanceSubGroupHeaderMaxTarget" : "High Target",
	"cashPoolingbalanceSubGroupHeaderIndirect" : "Indirect"	,
	
	"cashPoolingbalanceSubGroupAccountHeaderAccountNumber" : "Account Number",
	"cashPoolingbalanceSubGroupAccountHeaderDescription" : "Description",
	"cashPoolingbalanceSubGroupAccountHeaderSubGroupPivot" : "Pivot",
	
	"valueToday" :"Value today",
	"valueOneBusinessDay" : "Value one business day from today",
	"valueOneBusinessDayCADdeal" : "Value one business day from today for CAD deal",
	"valueTwoBusinessDay" : "Value two business days from today",
		
	// KTP
	"comptesCentralisateurs" : "Centralizing Accounts",
	"comptesCentralises" : "Centralized Accounts",
	"retrieveEntityNameError" : "An error has occured when retrieving entity name from account number.",
	
	"invalidAccountNumberForBeneficiary" : "You have entered special characters. Only alphanumeric characters are allowed.",
	"invalidCashEntitlementMessage": "Atleast one entitlement has to be selected",
	"invalidContactNumber" :"This is not a valid contact number. Only numbers and special characters '-', '+' and '()' are allowed for this field.",
	"maxAmountGreaterThanMinAmountError" :"The 'Max Amount' (${0}) should be greater than the 'Min Amount' (${1}).",
	"invalidCashSubsidiaryMessage": "Please select a Default subsidiary",
	"fileSizeExceeded": "The action could not be executed because the uploaded file exceeds allocated uploaded size 10 Mb."
})