/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a
 * bank on behalf of its corporate customer (an importer; applicant) for procured goods or services. A
 *  payment is released to the exporter against a presentation of specified documentation and in accord
 * ance with the terms of the letter of credit.  The ILC reflects the transaction request from the pers
 * pective of an importer and the importer's bank, typically known as the issuing bank.  'Issuance reque
 * st' is the initial event that creates the ILC transaction event. This event could only be created onc
 * e per ILC. If changes to the basic details of the ILC are needed, an 'Amendment request' event could
 * be created. Once the beneficiary submits their documents and claims the payment, a 'Claims Received' eve
 * nt is created. The 'Amend' and 'Claims Received' events can be created multiple times and at any point
 * in the ILC lifecycle prior to its expiry.  Issuance request can be for the final issuance of letter of c
 * redit by the issuing bank or if this request is marked as \"Provisional\", then it is for vetting the te
 * xt of the letter of credit by the issuing bank. On finalisation of the text between the corporate customer
 * and the bank, the actual letter of credit will be issued by the bank.  There are two kinds of IDs in thi
 * s API: id and eventId. The eventId is the identifier returned for events such as 'Issuance', 'Amendment'
 *  and 'Claims Received'. The id is the identifier returned for the ILC master and it is created together
 *  with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendm
 * ent' and 'Claims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionAddress } from './address';


/**
 * The name and address details of the applicant. If the mode of transmission is selected as SWIFT during
 * the letter of credit creation, the information in address line 4 will be ignored
 */
export interface ApplicantOptional {
    /**
     * The shortcode for the applicant entity. This is a conditional mandatory in case a user is linked to one or more entity
     */
    entityShortName?: string;
    /**
     * The full name of the applicant entity
     */
    entityName?: string;
    address?: TransactionAddress;
}
