/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by
 *  a bank on behalf of its corporate customer (an importer; applicant) for procured goods or servic
 * es. A payment is released to the exporter against a presentation of specified documentation and
 * in accordance with the terms of the letter of credit.  The ILC reflects the transaction request f
 * rom the perspective of an importer and the importer's bank, typically known as the issuing bank.
 * 'Issuance request' is the initial event that creates the ILC transaction event. This event could
 * only be created once per ILC. If changes to the basic details of the ILC are needed, an 'Amendmen
 * t request' event could be created. Once the beneficiary submits their documents and claims the pa
 * yment, a 'Claims Received' event is created. The 'Amend' and 'Claims Received' events can be crea
 * ted multiple times and at any point in the ILC lifecycle prior to its expiry.  Issuance request c
 * an be for the final issuance of letter of credit by the issuing bank or if this request is marked
 *  as \"Provisional\", then it is for vetting the text of the letter of credit by the issuing bank.
 * On finalisation of the text between the corporate customer and the bank, the actual letter of cre
 * dit will be issued by the bank.  There are two kinds of IDs in this API: id and eventId. The even
 * tId is the identifier returned for events such as 'Issuance', 'Amendment' and 'Claims Received'.
 * The id is the identifier returned for the ILC master and it is created together with the 'Issuanc
 * e' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendment' and 'C
 * laims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Additional fields captured for template updation
 */
export interface ImportLetterOfCreditTemplateUpdateProperties {
    /**
     * The description of the template given by the customer
     */
    templateDescription?: string;
}
