/**
 * Import Letter of Credit
 * _Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on behalf of
 * its corporate customer (an importer; applicant) for procured goods or services. A payment is released to the exporter
 *  against a presentation of specified documentation and in accordance with the terms of the letter of credit._  _The
 * ILC reflects the transaction request from the perspective of an importer and the importer's bank, typically known as
 *  the issuing bank._  _'Issuance request' is the initial event that creates the ILC transaction event. This event cou
 * ld only be created once per ILC. If changes to the basic details of the ILC are needed, an 'Amendment request' event
 * could be created. Once the beneficiary submits their documents and claims the payment, a 'Claims Received' event is c
 * reated. The 'Amend' and 'Claims Received' events can be created multiple times and at any point in the ILC lifecycle p
 * rior to its expiry._  _Issuance request can be for the final issuance of letter of credit by the issuing bank or if th
 * is request is marked as "Provisional", then it is for vetting the text of the letter of credit by the issuing bank. On
 *  finalisation of the text between the corporate customer and the bank the actual letter of credit will be issued by th
 * e bank._  _There are two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events s
 * uch as 'Issuance', 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is cre
 * ated together with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendment'
 * and 'Claims Received' events._
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Amount } from './amount';
import { MasterIdentity } from './masterIdentity';
import { ProductStatus } from './productStatus';


/**
 * Import Letter of Credit Master List
 */
export class ImportLetterofCreditMasterInquiry {
  id?: MasterIdentity;
  /**
   * The short code for the Applicant Entity
   */
  entityShortName?: string;
  /**
   * The full name of the entity
   */
  entityName?: string;
  /**
   * Full name of the Applicant
   */
  applicant?: string;
  /**
   * The reference id for the letter of credit, that has been assigned by the Bank
   */
  bankReference?: string;
  /**
   * The reference id assigned by the applicant for the letter of credit
   */
  senderReference?: string;
  /**
   * Name of the beneficiary
   */
  beneficiary?: string;
  letterofCreditAmount?: Amount;
  /**
   * Date on which the letter of credit was approved and issued by the bank, in ISO 8601 format yyyy-mm-dd
   */
  issueDate?: string;
  /**
   * Date on which the letter of credit is set to expire, in ISO 8601 format yyyy-mm-dd
   */
  expiryDate?: string;
    productStatus?: ProductStatus;
}
