/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a b
 * ank on behalf of its corporate customer (an importer; applicant) for procured goods or servi
 * ces. A payment is released to the exporter against a presentation of specified documentation
 *  and in accordance with the terms of the letter of credit.  The ILC reflects the transaction
 *  request from the perspective of an importer and the importer's bank, typically known as the
 *  issuing bank.  'Issuance request' is the initial event that creates the ILC transaction eve
 * nt. This event could only be created once per ILC. If changes to the basic details of the IL
 * C are needed, an 'Amendment request' event could be created. Once the beneficiary submits th
 * eir documents and claims the payment, a 'Claims Received' event is created. The 'Amend' and 'Claims
 *  Received' events can be created multiple times and at any point in the ILC lifecycle prior to it
 * s expiry.  Issuance request can be for the final issuance of letter of credit by the issuing ban
 * k or if this request is marked as \"Provisional\", then it is for vetting the text of the letter
 *  of credit by the issuing bank. On finalisation of the text between the corporate customer and th
 * e bank, the actual letter of credit will be issued by the bank.  There are two kinds of IDs in t
 * his API: id and eventId. The eventId is the identifier returned for events such as 'Issuance', 'A
 * mendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is c
 * reated together with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event
 * and multiple 'Amendment' and 'Claims Received' events.
 *
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Import letter of credit templates
 */
export interface ImportLetterofCreditTemplatesEnquiry {
    /**
     * The short code for the applicant entity
     */
    entityShortName?: string;
    /**
     * The full name of the applicant entity
     */
    entityName?: string;
    /**
     * The unique template name given by the customer. If the template name is same as an existi
     * ng one, then the system should throw an error. If the unique name is given, it will create a new template
     */
    templateName?: string;
    /**
     * The description of the template given by the customer
     */
    templateDescription?: string;
    /**
     * Date on which the letter of credit template was created by the applicant, in ISO 8601 format yyyy-mm-ddThh:mm:ssZ
     */
    creationDate?: Date;
}
