/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by
 * a bank on behalf of its corporate customer (an importer; applicant) for procured goods or servi
 * ces. A payment is released to the exporter against a presentation of specified documentation an
 * d in accordance with the terms of the letter of credit.  The ILC reflects the transaction requ
 * est from the perspective of an importer and the importer's bank, typically known as the issuin
 * g bank.  'Issuance request' is the initial event that creates the ILC transaction event. This
 * event could only be created once per ILC. If changes to the basic details of the ILC are need
 * ed, an 'Amendment request' event could be created. Once the beneficiary submits their documen
 * ts and claims the payment, a 'Claims Received' event is created. The 'Amend' and 'Claims Rece
 * ived' events can be created multiple times and at any point in the ILC lifecycle prior to its
 *  expiry.  Issuance request can be for the final issuance of letter of credit by the issuing b
 * ank or if this request is marked as \"Provisional\", then it is for vetting the text of the l
 * etter of credit by the issuing bank. On finalisation of the text between the corporate custo
 * mer and the bank, the actual letter of credit will be issued by the bank.  There are two kind
 * s of IDs in this API: id and eventId. The eventId is the identifier returned for events such
 * as 'Issuance', 'Amendment' and 'Claims Received'. The id is the identifier returned for the I
 * LC master and it is created together with the 'Issuance' event. A master ILC transaction can h
 * ave one 'Issuance' event and multiple 'Amendment' and 'Claims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlternateApplicantDetails } from './alternateApplicantDetails';
import { Amount } from './amount';
import { ApplicantOptional } from './applicantOptional';
import { Attachments } from './attachments';
import { Bank } from './bank';
import { BankInstructions } from './bankInstructions';
import { Beneficiary } from './beneficiary';
import { Charge } from './charge';
import { Confirmation } from './confirmation';
import { IssuingBank } from './issuingBank';
import { LcDetailsSave } from './lcDetailsSave';
import { LcTypes } from './lcTypes';
import { LicenseDetails } from './licenseDetails';
import { NarrativeSave } from './narrativeSave';
import { OtherDetails } from './otherDetails';
import { PaymentDetails } from './paymentDetails';
import { Revolving } from './revolving';
import { Shipment } from './shipment';
import { Tolerance } from './tolerance';


/**
 * Save Import letter of credit as a template
 */
export interface ImportLetterOfCreditTemplateTransaction {
    otherDetails?: OtherDetails;
    lcDetails?: LcDetailsSave;
    lcType?: LcTypes;
    applicant?: ApplicantOptional;
    alternateApplicant?: AlternateApplicantDetails;
    beneficiary?: Beneficiary;
    amount?: Amount;
    amountTolerance?: Tolerance;
    confirmation?: Confirmation;
    chargeDetail?: Charge;
    revolving?: Revolving;
    paymentDetails?: PaymentDetails;
    shipment?: Shipment;
    issuingBank?: IssuingBank;
    advisingBank?: Bank;
    adviseThroughBank?: Bank;
    license?: LicenseDetails;
    narrative?: NarrativeSave;
    bankInstructions?: BankInstructions;
    attachments?: Attachments;
}
