/**
 * Import Letter of Credit
 * _Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on behalf of
 * its corporate customer (an importer; applicant) for procured goods or services. A payment is released to the exporter
 *  against a presentation of specified documentation and in accordance with the terms of the letter of credit._  _The ILC
 *  reflects the transaction request from the perspective of an importer and the importer's bank, typically known as the
 * issuing bank._  _'Issuance request' is the initial event that creates the ILC transaction event. This event could only
 * be created once per ILC. If changes to the basic details of the ILC are needed, an 'Amendment request' event could be
 * created. Once the beneficiary submits their documents and claims the payment, a 'Claims Received' event is created. Th
 * e 'Amend' and 'Claims Received' events can be created multiple times and at any point in the ILC lifecycle prior to it
 * s expiry._  _Issuance request can be for the final issuance of letter of credit by the issuing bank or if this reques
 * t is marked as "Provisional", then it is for vetting the text of the letter of credit by the issuing bank. On finalis
 * ation of the text between the corporate customer and the bank the actual letter of credit will be issued by the bank.
 * _  _There are two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events such as
 * 'Issuance', 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is created
 * together with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendment' a
 * nd 'Claims Received' events._
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicableRule } from './applicableRule';


/**
 * LC details object definition
 */
export class LcDetails {
    /**
     * The reference id assigned by the applicant for the letter of credit
     */
    senderReference?: string;
    /**
     * The date on which the letter of credit is set to expire, in ISO8601 format yyyy-mm-dd. This field is mandatory for
     * submission of a LC transaction or a template
     */
    expiryDate: string;
    /**
     * The expiry place for the letter of credit. This field is mandatory for submission of a LC transaction or a template
     */
    expiryPlace: string;
    /**
     * The mode through which the bank will transmit the letter of credit. This field is mandatory for submission of a LC
     * transaction or a template
     */
    issueBy: LcDetails.IssueByEnum;
    applicableRule: ApplicableRule;
}
export namespace LcDetails {
    export type IssueByEnum = 'COURIER' | 'SWIFT' | 'TELEX';
    export const IssueByEnum = {
        COURIER: 'COURIER' as IssueByEnum,
        SWIFT: 'SWIFT' as IssueByEnum,
        TELEX: 'TELEX' as IssueByEnum
    };
}
