/**
 * Transaction Approvals
 * The Transaction Approvals API allows the corporate user to approve or reject a transaction pending for approval. This API request is based on the users access to the relevant accounts, corporate entities, as well as the transfer types.
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReauthValue } from './reauthValue';


/**
 * Reauth value and reference key array object definition
 */
export interface Reauth extends Array<ReauthValue> {
}
