/**
 * Import Letter of Credit
 * _Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on behalf of
 * its corporate customer (an importer; applicant) for procured goods or services. A payment is released to the exporter
 * against a presentation of specified documentation and in accordance with the terms of the letter of credit._  _The ILC
 *  reflects the transaction request from the perspective of an importer and the importer's bank, typically known as the
 *  issuing bank._  _'Issuance request' is the initial event that creates the ILC transaction event. This event could only
 * be created once per ILC. If changes to the basic details of the ILC are needed, an 'Amendment request' event could be
 * created. Once the beneficiary submits their documents and claims the payment, a 'Claims Received' event is created. The
 * 'Amend' and 'Claims Received' events can be created multiple times and at any point in the ILC lifecycle prior to its
 * expiry._  _Issuance request can be for the final issuance of letter of credit by the issuing bank or if this request is
 * marked as "Provisional", then it is for vetting the text of the letter of credit by the issuing bank. On finalisation of
 * the text between the corporate customer and the bank the actual letter of credit will be issued by the bank._  _There are
 * two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events such as 'Issuance',
 * 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is created together with the
 *  'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendment' and 'Claims Received'
 * events._
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Details of the Goods shipment covered under the Letter of Credit
 */
export class Shipment {
    /**
     * The originating point of the goods covered under the Import Letter of Credit
     */
    from?: string;
    /**
     * The port or airport of loading
     */
    portOfLoading?: string;
    /**
     * The port or airport of unloading
     */
    portOfDischarge?: string;
    /**
     * The destination point of the goods covered under the Import letter of credit
     */
    to?: string;
    /**
     * Specifies if partial shipments are allowed or if a single shipment is to be made
     */
    partialShipment?: Shipment.PartialShipmentEnum;
    /**
     * Specifies if transhipments are allowed or if the shipping has to be in a single leg
     */
    transhipment?: Shipment.TranshipmentEnum;
    /**
     * The final date by when the shipment needs to be completed for the quantity mentioned in the letter of credit,
     *  in ISO 8601 format yyyy-mm-dd. Either use this field or period to specify the shipment date of the goods.
     */
    date?: string;
    /**
     * Details of the shipment period. Either use this field or date to specify the shipment date of the goods
     */
    period?: string;
    /**
     * The purchase terms/inco terms used in the Import letter of credit. (ex. CFR = Cost and Freight)
     */
    incoTerms?: string;
    /**
     * The location from where the purchase terms will begin to take effect
     */
    incoPlace?: string;
}
export namespace Shipment {
    export type PartialShipmentEnum = 'ALLOWED' | 'NOT-ALLOWED' | 'CONDITIONAL';
    export const PartialShipmentEnum = {
        ALLOWED: 'ALLOWED' as PartialShipmentEnum,
        NOTALLOWED: 'NOT-ALLOWED' as PartialShipmentEnum,
        CONDITIONAL: 'CONDITIONAL' as PartialShipmentEnum
    };
    export type TranshipmentEnum = 'ALLOWED' | 'NOT-ALLOWED' | 'CONDITIONAL';
    export const TranshipmentEnum = {
        ALLOWED: 'ALLOWED' as TranshipmentEnum,
        NOTALLOWED: 'NOT-ALLOWED' as TranshipmentEnum,
        CONDITIONAL: 'CONDITIONAL' as TranshipmentEnum
    };
}
