/**
 * Import Letter of Credit
 * _Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on behalf
 * of its corporate customer (an importer; applicant) for procured goods or services. A payment is released to the exporter
 *  against a presentation of specified documentation and in accordance with the terms of the letter of credit._  _The ILC
 *  reflects the transaction request from the perspective of an importer and the importer's bank, typically known as the
 * issuing bank._  _'Issuance request' is the initial event that creates the ILC transaction event. This event could only
 * be created once per ILC. If changes to the basic details of the ILC are needed, an 'Amendment request' event could be
 * created. Once the beneficiary submits their documents and claims the payment, a 'Claims Received' event is created. The
 *  'Amend' and 'Claims Received' events can be created multiple times and at any point in the ILC lifecycle prior to its
 *  expiry._  _Issuance request can be for the final issuance of letter of credit by the issuing bank or if this request i
 * s marked as "Provisional", then it is for vetting the text of the letter of credit by the issuing bank. On finalisation
 * of the text between the corporate customer and the bank the actual letter of credit will be issued by the bank._  _There
 *  are two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events such as 'Issuance',
 * 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is created together with th
 * e 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple 'Amendment' and 'Claims Received'
 * events._
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Bill of Exchange details for the Letter of Credit. Either of the maturity date or (period, frequency ,fromAfter, start) should be passed
 */
export class Tenor {
     /** specifies the type of sight payment. This value should always be sent as SIGHT */
    sight?: string;
    /**
     * Specifies the maturity date in case the letter of credit is not of the SIGHT-PAYMENT type
     */
    maturityDate?: string;
    /**
     * The period number of the tenor. This must be blank if maturity date under Tenor is populated
     */
    period?: number;
    /**
     * Tenor period following this convention (D)ays, (W)eek , (M)onth , (Y)ear. This is the calendar period for the frequency
     * value. This must be blank if maturity date under Tenor is populated
     */
    frequency?: Tenor.FrequencyEnum;
    /**
     * Specifies how the tenor period is to be calculated from the tenor start date. This must be blank if maturity date
     * under Tenor is populated
     */
    fromAfter?: Tenor.FromAfterEnum;
    /**
     * Specifies the trigger event for start of the  tenor period. This must be blank if maturity date under Tenor is populated
     */
    start?: Tenor.StartEnum;
    /**
     * Contains the tenor start condition, in case the event for tenor trigger is Other. This will be null for all other events.
     * This must be blank if maturity date under Tenor is populated
     */
    narrative?: string;
}
export namespace Tenor {
    export type FrequencyEnum = 'D' | 'W' | 'M' | 'Y';
    export const FrequencyEnum = {
        D: 'D' as FrequencyEnum,
        W: 'W' as FrequencyEnum,
        M: 'M' as FrequencyEnum,
        Y: 'Y' as FrequencyEnum
    };
    export type FromAfterEnum = 'AFTER' | 'FROM';
    export const FromAfterEnum = {
        AFTER: 'AFTER' as FromAfterEnum,
        FROM: 'FROM' as FromAfterEnum
    };
    export type StartEnum = 'AIR-WAYBILL' | 'ARRIVAL-OF-GOODS' | 'BILL-OF-EXCHANGE' | 'BILL-OF-LADING' | 'INVOICE' |
              'SHIPMENT-DATE' | 'SIGHT' | 'OTHER' ;
    export const StartEnum = {
        AIRWAYBILL: 'AIR-WAYBILL' as StartEnum,
        ARRIVALOFGOODS: 'ARRIVAL-OF-GOODS' as StartEnum,
        BILLOFEXCHANGE: 'BILL-OF-EXCHANGE' as StartEnum,
        BILLOFLADING: 'BILL-OF-LADING' as StartEnum,
        INVOICE: 'INVOICE' as StartEnum,
        SHIPMENTDATE: 'SHIPMENT-DATE' as StartEnum,
        SIGHT: 'SIGHT' as StartEnum,
        OTHER: 'OTHER' as StartEnum
    };
}
