/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on
 * behalf of its corporate customer (an importer; applicant) for procured goods or services. A payment is
 * released to the exporter against a presentation of specified documentation and in accordance with the
 * terms of the letter of credit.  The ILC reflects the transaction request from the perspective of an importer
 *  and the importer's bank, typically known as the issuing bank.  'Issuance request' is the initial event that
 * creates the ILC transaction event. This event could only be created once per ILC. If changes to the basic
 * details of the ILC are needed, an 'Amendment request' event could be created. Once the beneficiary submits
 * their documents and claims the payment, a 'Claims Received' event is created. The 'Amend' and 'Claims Received'
 * events can be created multiple times and at any point in the ILC lifecycle prior to its expiry.  Issuance request
 * can be for the final issuance of letter of credit by the issuing bank or if this request is marked as
 * \"Provisional\", then it is for vetting the text of the letter of credit by the issuing bank. On finalisation
 * of the text between the corporate customer and the bank, the actual letter of credit will be issued by the bank.
 * There are two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events such as
 *  'Issuance', 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is
 * created together with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple
 * 'Amendment' and 'Claims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The transaction sub type code values. Possible transaction sub type code values:  * N003_* = *
 * * N003_01 = Increase * N003_02 = Decrease * N003_03 = Terms * N003_04 = Upload * N003_05 = Release
 * * N003_06 = B2B * N003_07 = Generation * N003_08 = Disc. Acknowledged * N003_09 = Disc. Not Acknowedged
 * * N003_10 = Version * N003_11 = Free Format * N003_12 = Transfer * N003_13 = Approved * N003_14 = Not Approved
 * * N003_15 = Order Close * N003_16 = Payment Acknowledged * N003_17 = Payment Not Acknowledged * N003_18 = Update
 * * N003_19 = Assignee * N003_20 = Extend * N003_21 = Pay * N003_22 = Cancel * N003_23 = Confirm
 * * N003_24 = Correspondence * N003_25 = Request For Settlement * N003_26 = Rollover Increase
 * * N003_27 = Rollover Decrease * N003_28 = Rollover * N003_29 = Reverse * N003_30 = Rebook * N003_31 = Drawdown
 * * N003_32 = Uptake * N003_33 = Extend * N003_34 = Split * N003_35 = Negotiation/Discount
 * * N003_36 = Send for Payment/Acceptance * N003_37 = Amend Instructions * N003_38 = Partial Payment
 * * N003_39 = Final/Full Payment * N003_40 = Drawdown * N003_41 = Acceptance * N003_42 = Acknowledged
 * * N003_43 = Not Acknowledged * N003_44 = Present Acknowledged * N003_45 = Present Not Acknowledged
 * * N003_46 = Accepted * N003_47 = Rejected * N003_48 = Short Payoff, Third Party * N003_49 = Actual / Actual
 * * N003_50 = Net Yield (Scheduled / Actual) * N003_51 = Yield All (Actual / Scheduled)
 * * N003_52 = Scheduled / Scheduled * N003_53 = Open * N003_54 = In Process * N003_55 = Rejected
 * * N003_56 = Rejected Under Review * N003_57 = Approved * N003_58 = Sent * N003_59 = Failed * N003_60 = Passed
 * * N003_61 = Terminate * N003_62 = Accept Claim * N003_63 = Reject Claim * N003_64 = Resubmitted
 * * N003_65 = Request for Book Off * N003_66 = Accept * N003_67 = Reject * N003_68 = Cancellation Request
 * * N003_69 = Buyer Initiated * N003_70 = Resubmission Acknowledgment * N003_71 = Resubmission Non Acknowledgement
 * * N003_72 = Invoice Acknowledged * N003_73 = Invoice Not Acknowledged * N003_74 = Early Payment Request
 * * N003_75 = Early Payment Refusal * N003_76 = Early Payment Acknowledged * N003_77 = Early Payment Not Acknowledged
 * * N003_78 = Financing Request * N003_79 = Financing Request Refusal * N003_80 = Early Payment
 * * N003_81 = Dealer Financing * N003_82 = Invoice Financing * N003_84 = Cleared * N003_99 = Other
 * * N003_85 = Approved Payable Financing Requested * N003_86 = Approved Payable Financing Request Refusal
 * * N003_88 = Wording Accepted * N003_89 = Wording Rejected * N003_91 = Offer Acknowledged
 * * N003_92 = Offer Not Acknowledged * N003_93 = Payment Split * N003_94 = Request for Payment
 * * N003_95 = Request for Acceptance * N003_96 = Request for Cancellation * N003_83 = Seller Initiated
 *  * N003_97 = Request for Repricing * N003_87 = Generate Remittance Letter
 * * N003_90 = APF Seller Upload Invoice Accept * N003_98 = APF Seller Upload Invoice Reject
 * * N003_A0 = APF Seller Upload Finance Request * N003_A1 = APF Seller Upload Finance Refusal
 * * N003_A2 = APF Buyer Upload Finance Request * N003_A3 = APF Buyer Upload Invoice Finance Refusal
 * * N003_A4 = Finance Repayment Request * N003_A5 = Finance Repayment Request Refusal
 * * N003_A6 = Finance Repayment * N003_A7 = Liquidation * N003_A8 = Rollback * N003_A9 = Takeup
 * * N003_B0 = OTHR * N003_B1 = Swingline
 */
export type TransactionSubType = string;
