/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank
 * on behalf of its corporate customer (an importer; applicant) for procured goods or services. A payment is
 * released to the exporter against a presentation of specified documentation and in accordance with the terms
 * of the letter of credit.  The ILC reflects the transaction request from the perspective of an importer and
 * the importer's bank, typically known as the issuing bank.  'Issuance request' is the initial event that
 * creates the ILC transaction event. This event could only be created once per ILC. If changes to the basic
 * details of the ILC are needed, an 'Amendment request' event could be created. Once the beneficiary submits
 * their documents and claims the payment, a 'Claims Received' event is created. The 'Amend' and
 * 'Claims Received' events can be created multiple times and at any point in the ILC lifecycle prior to
 * its expiry.  Issuance request can be for the final issuance of letter of credit by the issuing bank or
 * if this request is marked as \"Provisional\", then it is for vetting the text of the letter of credit by
 * the issuing bank. On finalisation of the text between the corporate customer and the bank, the actual
 *  letter of credit will be issued by the bank.  There are two kinds of IDs in this API: id and eventId.
 * The eventId is the identifier returned for events such as 'Issuance', 'Amendment' and 'Claims Received'.
 * The id is the identifier returned for the ILC master and it is created together with the 'Issuance' event.
 *  A master ILC transaction can have one 'Issuance' event and multiple 'Amendment' and 'Claims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Sub transaction status code for the last processed step for the letter of credit. Possible transaction sub status
 *  code values: * N015_01 = Draft * N015_02 = Pending Verify * N015_03 = Pending Authorise * N015_04 = Pending Send
 * * N015_05 = Sent * N015_06 = Post Dated * N015_07 = Completed * N015_08 = Rejected * N015_09 = Entry
 * * N015_10 = In-Process * N015_11 = Recurring * N015_12 = Recurring Pending * N015_13 = Post Dated Pending
 * * N015_14 = Sent to the Bank * N015_15 = Sending Failed * N015_16 = Cancelled * N015_17 = In-Process
 * * N015_18 = Returned * N015_19 = Customer Deleted * N015_21 = Process Failed * N015_22 = Received
 * * N015_23 = Receive Failed * N015_24 = Awaiting Bank Confirmation * N015_25 = Failed * N015_99 = Undefined
 */
export type TransactionSubStatus = string;
