/**
 * Import Letter of Credit
 * Import Letter of Credit (ILC) is an undertaking to pay to a beneficiary (an exporter), issued by a bank on
 * behalf of its corporate customer (an importer; applicant) for procured goods or services. A payment is
 * released to the exporter against a presentation of specified documentation and in accordance with the terms
 * of the letter of credit.  The ILC reflects the transaction request from the perspective of an importer and
 * the importer's bank, typically known as the issuing bank.  'Issuance request' is the initial event that
 * creates the ILC transaction event. This event could only be created once per ILC. If changes to the basic
 * details of the ILC are needed, an 'Amendment request' event could be created. Once the beneficiary submits
 * their documents and claims the payment, a 'Claims Received' event is created. The 'Amend' and 'Claims Received'
 * events can be created multiple times and at any point in the ILC lifecycle prior to its expiry.  Issuance request
 * can be for the final issuance of letter of credit by the issuing bank or if this request is marked as
 * \"Provisional\", then it is for vetting the text of the letter of credit by the issuing bank. On finalisation
 * of the text between the corporate customer and the bank, the actual letter of credit will be issued by the bank.
 * There are two kinds of IDs in this API: id and eventId. The eventId is the identifier returned for events such as
 * 'Issuance', 'Amendment' and 'Claims Received'. The id is the identifier returned for the ILC master and it is
 * created together with the 'Issuance' event. A master ILC transaction can have one 'Issuance' event and multiple
 * 'Amendment' and 'Claims Received' events.
 *
 * OpenAPI spec version: 1.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The transaction type code values. Possible transaction type code values:
 * * N002_* = * * N002_01 = New * N002_02 = Update * N002_03 = Amend * N002_04 = Extend * N002_05 = Accept
 *  * N002_06 = Confirm * N002_07 = Consent * N002_08 = Settle * N002_09 = Transfer * N002_10 = Drawdown
 * * N002_11 = Reverse * N002_12 = Delete * N002_13 = Message * N002_14 = Cancel * N002_15 = Reporting
 * * N002_16 = Reinstate * N002_17 = Purge * N002_18 = Presentation * N002_19 = Assign * N002_20 = Register
 * * N002_21 = Resubmission * N002_22 = Report Activity * N002_23 = Prepayment * N002_24 = Charging Advice
 * * N002_82 = Error Report * N002_85 = Invoice Settle * N002_86 = Deal Name Change * N002_87 = Facility Name Change
 */
export type TransactionType = string;
