<?xml version="1.0" encoding="UTF-8"?>
<!--
##########################################################

Counter party association with Customer.

Copyright (c) 2000-2008 Misys (http://www.misys.com),
All Rights Reserved. 

version:   1.0
date:      22/07/16
author:    Jino Devasia
##########################################################
-->
<!DOCTYPE xsl:stylesheet [
  <!ENTITY nbsp "&#160;">
]>
<xsl:stylesheet 
		version="1.0" 
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
		xmlns:localization="xalan://com.misys.portal.common.localization.Localization"
		xmlns:securitycheck="xalan://com.misys.portal.common.security.GTPSecurityCheck"
		xmlns:jetspeedresources="xalan://com.misys.portal.core.util.JetspeedResources"
		xmlns:utils="xalan://com.misys.portal.common.tools.Utils"
		xmlns:defaultresource="xalan://com.misys.portal.common.resources.DefaultResourceProvider"
		exclude-result-prefixes="localization securitycheck utils defaultresource jetspeedresources">
	
	<xsl:param name="language">en</xsl:param>
  <xsl:param name="languages"/>
  <xsl:param name="nextscreen"/>
  <xsl:param name="option"/>
  <xsl:param name="action"/>
  <xsl:param name="token"/>
  <xsl:param name="password_mimimum_length"/><!-- password policy -->
  <xsl:param name="password_maximum_length"/>
  <xsl:param name="password_charset"/>
  <xsl:param name="password_autogenerated"/>
  <xsl:param name="password_display_disabled"/>
  <xsl:param name="email_required"/>
  <xsl:param name="displaymode">edit</xsl:param>
  <xsl:param name="collaborationmode">none</xsl:param> <!-- set to none, counterparty or bank, depending on whether we are in a collab summary screen  -->
  <xsl:param name="main-form-name">fakeform1</xsl:param>
  <xsl:param name="operation">SAVE_FEATURES</xsl:param>
  <xsl:param name="companyType"/>
  <xsl:param name="processdttm"/>
  <xsl:param name="isCounterparty">false</xsl:param>
  <xsl:param name="owner_name"/>
	<!-- Global Imports. -->
 	<xsl:include href="../../../core/xsl/common/system_common.xsl" />
 	<xsl:include href="../../../core/xsl/system/sy_jurisdiction.xsl" />
  	<xsl:include href="../../../core/xsl/common/maker_checker_common.xsl" />
  	<xsl:include href="../../../core/xsl/common/attachment_templates.xsl" />
		
	<xsl:output method="html" version="4.01" indent="no" encoding="UTF-8" omit-xml-declaration="yes" />
  	<xsl:template match="/">
   	<xsl:apply-templates select="static_beneficiary"/>
  	</xsl:template>
  	
  	 <xsl:template match="static_beneficiary">
	   <!-- Loading message  -->
	   <xsl:call-template name="loading-message"/>
	
		<div>
		    <xsl:attribute name="id"><xsl:value-of select="$displaymode"/></xsl:attribute>
		    
		    <xsl:call-template name="form-wrapper">
		    	<xsl:with-param name="name" select="$main-form-name"/>
		     	<xsl:with-param name="validating">Y</xsl:with-param>
		     	<xsl:with-param name="content">
		     		<xsl:call-template name="counterparty-general-details"/>
		     		<xsl:choose>
		   				<xsl:when test="$displaymode='edit' or $operation='CHECK_FEATURES'">
		   					<xsl:call-template name="customer-details"/>
		   				</xsl:when>
		   				<xsl:otherwise>
							<xsl:call-template name="customer-details-view"/>
						</xsl:otherwise>
		   			</xsl:choose>
		     	</xsl:with-param>
		   </xsl:call-template>
		   <xsl:if test="$canCheckerReturnComments = 'true'">
		     	<xsl:call-template name="comments-for-return-mc">
		     		<xsl:with-param name="value"><xsl:value-of select="return_comments"/></xsl:with-param>
		     	</xsl:call-template>
	    	</xsl:if>
	     <xsl:if test="$displaymode='edit' or $operation='CHECK_FEATURES'">
			<xsl:call-template name="maker-checker-menu">
				<xsl:with-param name="show-save">N</xsl:with-param>
			</xsl:call-template>
	    </xsl:if>
		   
		  	<xsl:call-template name="realform"/>
	    </div>
	<xsl:call-template name="js-imports"/>
 	
    </xsl:template>
    
    <xsl:template name="js-imports">
	  <xsl:call-template name="system-common-js-imports">
   		<xsl:with-param name="xml-tag-name">static_beneficiary</xsl:with-param>
		<xsl:with-param name="binding">misys.binding.system.cpty_company_asc</xsl:with-param>
		<xsl:with-param name="override-home-url">'/screen/<xsl:value-of select="$nextscreen"/>?option=<xsl:value-of select="$option"/>'</xsl:with-param>
	  </xsl:call-template>
 	</xsl:template>
  
  <xsl:template name="realform">
  <!-- Do not display this section when the counterparty mode is 'counterparty' -->
  <xsl:if test="$collaborationmode != 'counterparty'">
  <xsl:call-template name="form-wrapper">
   <xsl:with-param name="name">realform</xsl:with-param>
   <xsl:with-param name="method">POST</xsl:with-param>
   <xsl:with-param name="action"><xsl:value-of select="$contextPath"/><xsl:value-of select="$servletPath"/>/screen/<xsl:value-of select="$nextscreen"/></xsl:with-param>
    <xsl:with-param name="content">
     <div class="widgetContainer">
      <xsl:call-template name="hidden-field">
       <xsl:with-param name="name">operation</xsl:with-param>
       <xsl:with-param name="id">realform_operation</xsl:with-param>
       <xsl:with-param name="value" select="$operation"></xsl:with-param>
      </xsl:call-template>
      <xsl:call-template name="hidden-field">
       <xsl:with-param name="name">TransactionData</xsl:with-param>
      </xsl:call-template>
      <xsl:call-template name="hidden-field">
       	<xsl:with-param name="name">token</xsl:with-param>
       	<xsl:with-param name="value"><xsl:value-of select="$token"/></xsl:with-param>
      </xsl:call-template>
      <xsl:call-template name="hidden-field">
       	<xsl:with-param name="name">beneficiary_id</xsl:with-param>
       	<xsl:with-param name="value"><xsl:value-of select="beneficiary_id"/></xsl:with-param>
      </xsl:call-template>
      <xsl:call-template name="hidden-field">
       	<xsl:with-param name="name">tnxid</xsl:with-param>
       	<xsl:with-param name="value"><xsl:value-of select="tnx_id"/></xsl:with-param>
      </xsl:call-template>
      <xsl:call-template name="hidden-field">
       	<xsl:with-param name="name">processdttm</xsl:with-param>
       	<xsl:with-param name="value"><xsl:value-of select="$processdttm"/></xsl:with-param>
      </xsl:call-template>
     </div>
    </xsl:with-param>
   </xsl:call-template>
   </xsl:if>
  </xsl:template>
  
  <xsl:template name="customer-details">
  	<xsl:call-template name="fieldset-wrapper">
   		<xsl:with-param name="legend">XSL_HEADER_COMPANY_ASSIGNMENT</xsl:with-param>
   		<xsl:with-param name="content">
   		<xsl:call-template name="hidden-field">
		   		<xsl:with-param name="name">tnx_stat_code</xsl:with-param>
		   		<xsl:with-param name="value"><xsl:value-of select="tnx_stat_code"/></xsl:with-param>	      
		 	</xsl:call-template>		 	
   			<xsl:call-template name="multioption-group">
		        <xsl:with-param name="content">
		           <xsl:call-template name="radio-field">
					    <xsl:with-param name="label">XL_SYS_GENERATE_COMPANY</xsl:with-param>
					    <xsl:with-param name="name">cpty_cust_code</xsl:with-param>
					    <xsl:with-param name="id">cpty_cust_code_1</xsl:with-param>
					    <xsl:with-param name="value">01</xsl:with-param>
				   </xsl:call-template>
				   <xsl:call-template name="radio-field">
					    <xsl:with-param name="label">XSL_HEADER_COMPANY_LIST</xsl:with-param>
					    <xsl:with-param name="name">cpty_cust_code</xsl:with-param>
					    <xsl:with-param name="id">cpty_cust_code_2</xsl:with-param>
					    <xsl:with-param name="value">02</xsl:with-param>
			   	   </xsl:call-template>
			   	   
			   	   <xsl:if test="$displaymode='view'">
			   	   	<xsl:call-template name="input-field">
				   	   	<xsl:with-param name="value">
				   	   		<xsl:choose>
				   	   			<xsl:when test = "cpty_cust_code[.=02]">
				   	   				:<xsl:value-of select = "cpty_company" />
				   	   			</xsl:when>			   	   		
				   	   		</xsl:choose>
				   	   	</xsl:with-param>
			   	   	</xsl:call-template>
			   	   </xsl:if>
		        </xsl:with-param>
		    </xsl:call-template>
   			<div id="cpty_cust_div">
	  			<xsl:call-template name="select-field">
	    			<xsl:with-param name="label">COMPANY_LABEL</xsl:with-param>
	    			<xsl:with-param name="name">cpty_company</xsl:with-param>
	    			<xsl:with-param name="required">N</xsl:with-param>
	    			<xsl:with-param name="options">
	    		  	<xsl:for-each select="companies/company">
	     		  	<option>
	     		  		<xsl:attribute name="value"><xsl:value-of select="abbv_name"/></xsl:attribute>
	     		  		<xsl:value-of select="abbv_name"/>
	     		  	</option>
	    		  	</xsl:for-each>
	     		</xsl:with-param>
	     	</xsl:call-template>
	     </div>
   		</xsl:with-param>
   	</xsl:call-template>
     		
  </xsl:template>
  
  <xsl:template name="counterparty-general-details">
  
  <xsl:call-template name="fieldset-wrapper">
   		<xsl:with-param name="legend">XSL_HEADER_OWNER_COMP_DETAILS</xsl:with-param>
   		<xsl:with-param name="content">
	   		<xsl:call-template name="input-field">
					<xsl:with-param name="label">XSL_JURISDICTION_ABREVIATED_NAME</xsl:with-param>
					<xsl:with-param name="name">owner_customer_abbv_name</xsl:with-param>
					<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<xsl:call-template name="input-field">
					<xsl:with-param name="label">XSL_JURISDICTION_NAME</xsl:with-param>
					<xsl:with-param name="name">owner_name</xsl:with-param>
					<xsl:with-param name="value"><xsl:value-of select = "$owner_name" /></xsl:with-param>
					<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
		</xsl:with-param>
	</xsl:call-template>
  	<xsl:call-template name="fieldset-wrapper">
   		<xsl:with-param name="legend">XSL_HEADER_COUNTER_PARTY_DETAILS</xsl:with-param>
   		<xsl:with-param name="content">
   		
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_JURISDICTION_ABREVIATED_NAME</xsl:with-param>
				<xsl:with-param name="name">abbv_name</xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			 
			<!-- Name -->    
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_JURISDICTION_NAME</xsl:with-param>
				<xsl:with-param name="name">name</xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>	
			
			<!--FSCM Enabled -->
			<xsl:call-template name="input-field">
				 <xsl:with-param name="label">XSL_FSCM_ENABLED</xsl:with-param>
				 <xsl:with-param name="name">fscm_enabled</xsl:with-param>
				 <xsl:with-param name="value"><xsl:value-of
							select="localization:getDecode($language, 'N034', fscm_enabled)" /></xsl:with-param>
				 <xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			
			<!--Credit Note Enabled -->
		    <xsl:call-template name="input-field">
				 <xsl:with-param name="label">XSL_CN_ENABLED</xsl:with-param>
				 <xsl:with-param name="name">credit_note_enabled</xsl:with-param>
				 <xsl:with-param name="value"><xsl:value-of
							select="localization:getDecode($language, 'N034', credit_note_enabled)" /></xsl:with-param>
				 <xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<!--Buyer Role -->
			<xsl:call-template name="input-field">
				 <xsl:with-param name="label">XSL_BUYER_ROLE</xsl:with-param>
				 <xsl:with-param name="name">buyer_role</xsl:with-param>
				 <xsl:with-param name="value"><xsl:value-of
							select="localization:getDecode($language, 'N034', buyer_role)" /></xsl:with-param>
				 <xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>

			<!--Seller Role -->
			<xsl:call-template name="input-field">
				 <xsl:with-param name="label">XSL_SELLER_ROLE</xsl:with-param>
				 <xsl:with-param name="name">seller_role</xsl:with-param>
				 <xsl:with-param name="value"><xsl:value-of
							select="localization:getDecode($language, 'N034', seller_role)" /></xsl:with-param>
				 <xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
				
		  	<xsl:call-template name="input-field">
		  		<xsl:with-param name="label">XSL_JURISDICTION_COUNTERPARTY_COLLABORATION</xsl:with-param>
		   		<xsl:with-param name="name">access_opened</xsl:with-param>
			   	<xsl:with-param name="value"><xsl:value-of
							select="localization:getDecode($language, 'N034', access_opened)" /></xsl:with-param>
				 <xsl:with-param name="override-displaymode">view</xsl:with-param>
		  	</xsl:call-template>
		  	
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_JURISDICTION_COUNTERPARTY_ERP_ID</xsl:with-param>
				<xsl:with-param name="name">erp_id</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./erp_id"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_JURISDICTION_COUNTERPARTY_LEGAL_ID_NO</xsl:with-param>
				<xsl:with-param name="name">legal_id_no</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./legal_id_no"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_JURISDICTION_COUNTERPARTY_ACCOUNT</xsl:with-param>
				<xsl:with-param name="name">account</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./account"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_BENEFICIARY_SWIFT_BIC_CODE</xsl:with-param>
				<xsl:with-param name="name">bank_iso_code</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./bank_iso_code"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			
			  <!-- BANK NAME -->
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_BENEFICIARY_BANK_NAME</xsl:with-param>
				<xsl:with-param name="name">bank_name</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./bank_name"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<!-- BANK ADDRESS -->
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_BENEFICIARY_BANK_STREET</xsl:with-param>
				<xsl:with-param name="name">bank_address_line_1</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./bank_address_line_1"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
				</xsl:call-template>
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_BENEFICIARY_BANK_TOWN</xsl:with-param>
				<xsl:with-param name="name">bank_address_line_2</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./bank_address_line_2"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
			<xsl:call-template name="input-field">
				<xsl:with-param name="label">XSL_BENEFICIARY_BANK_COUNTRY_SUB_DIV</xsl:with-param>
				<xsl:with-param name="name">bank_dom</xsl:with-param>
				<xsl:with-param name="value"><xsl:value-of select="./bank_dom"/></xsl:with-param>
				<xsl:with-param name="override-displaymode">view</xsl:with-param>
			</xsl:call-template>
   		</xsl:with-param>
   	</xsl:call-template>
  </xsl:template>
  <xsl:template name="customer-details-view">
  	<xsl:call-template name="fieldset-wrapper">
   		<xsl:with-param name="legend">XSL_HEADER_COMPANY_ASSIGNMENT</xsl:with-param>
   		<xsl:with-param name="content">
		 	<xsl:choose>
   				<xsl:when test="cpty_cust_code = '01'">
   					<xsl:call-template name="input-field">
				 		<xsl:with-param name="label">XL_SYS_GENERATE_COMPANY_LABEL</xsl:with-param>
						<xsl:with-param name="value"><xsl:value-of select = "beneficiary_company_abbv_name" /></xsl:with-param>
						<xsl:with-param name="override-displaymode">view</xsl:with-param>
					</xsl:call-template>
   				</xsl:when>
   				<xsl:otherwise>
   					<xsl:call-template name="input-field">
				 		<xsl:with-param name="label">XSL_HEADER_COMPANY_LIST_LABEL</xsl:with-param>
						<xsl:with-param name="value"><xsl:value-of select = "beneficiary_company_abbv_name" /></xsl:with-param>
						<xsl:with-param name="override-displaymode">view</xsl:with-param>
					</xsl:call-template>
				</xsl:otherwise>
   			</xsl:choose>
   		</xsl:with-param>
   	</xsl:call-template>
  </xsl:template>
		
</xsl:stylesheet>