dojo.provide("misys.binding.help");

dojo.require("dijit.ProgressBar");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.data.ItemFileReadStore");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.Editor");
dojo.require("dojox.editor.plugins.TablePlugins");
dojo.require("dijit._editor.plugins.LinkDialog");
dojo.require("misys.form.SimpleTextarea"); 
dojo.require("misys.form.common");
dojo.require("misys.validation.common");
dojo.require("misys.help");